version: '3.4'
services:
  client:
    image: damienaymon/sdd_client_demo
    build:
      dockerfile: ./Dockerfile
    container_name: sdd_client_demo
    ports: 
      - 8888:8888
    volumes:
      - ./:/code/
      # Add whatever files you need here