version: '3.4'
services:
  client:
    image: dsccadminch/lomas_client_dev
    build:
      dockerfile: ./Dockerfile_client
      target: lomas_client_dev
      context: ../
    container_name: lomas_client_dev
    ports:
      - 8888:8888
    volumes:
      - ./:/code/
      - ./configs/:/root/.jupyter/
      # Add whatever files you need here
