[tool.black]
line-length = 79
include = '\.pyi?$'

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 79
split_on_trailing_comma = true
src_paths = ["lomas_client"]

[tool.mypy]
disable_error_code = ["import-untyped", "import-not-found", "attr-defined"]

[tool.pylint.MASTER]
ignore-patterns = ""

[tool.pylint."MESSAGES CONTROL"]
disable = [
    "E0401",  # import-error
    "C0114",  # missing-module-docstring
    "W0102",  # dangerous-default-value
    "R0913",  # too-many-arguments
    "R0914"   # too-many-locals
]