apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lomas_client.fullname" . }}
  labels:
    {{- include "lomas_client.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "lomas_client.selectorLabels" . | nindent 6 }}
  replicas: 1
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "lomas_client.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "lomas_client.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      
      containers:
      - name: {{ .Chart.Name }}
        securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
          - name: http
            containerPort: 8888
            protocol: TCP
        volumeMounts:
          - name: secrets
            readOnly: True
            mountPath: "/root/.jupyter/"
        resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: secrets
          projected:
            sources:
            - secret:
                name: {{ include "lomas_client.fullname" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }} 
