
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lomas_client.fullname" . }}
  labels:
    {{- include "lomas_client.labels" . | nindent 4 }}
stringData:
  jupyter_notebook_config.py: |
    from jupyter_server.auth import passwd
    c = get_config() # noqa

    password = {{ .Values.password }}
    c.NotebookApp.password = passwd(password)