version: '3.4'
services:
  sdd_poc_server:
    image: sdd_server_dev
    build:
      dockerfile: ./Dockerfile
    container_name: sdd_server_dev
    ports:
      - 80:80
    restart: always
    volumes:
      - ./src:/code/
      - ./configs/example_config.yaml:/usr/sdd_poc_server/runtime.yaml
    depends_on:
      - mongodb
    networks:
      - sdd-network
  mongodb:
    container_name: mongodb
    image: mongodb/mongodb-community-server:6.0-ubi8
    # Use only if volume is not a docker volume but a bind mount (e.g. ./data/:/data/db/)
    # The reason has to do with permissions (see https://stackoverflow.com/questions/29245216/write-in-shared-volumes-docker/29251160#29251160)
    # Still unclear why just setting chmod 777 ./data does not solve the issue.
    #user: 1000:1000
    ports:
      - 27017:27017
    networks:
      - sdd-network
    volumes:
      - mongodata:/data/db/
networks:
  sdd-network:
    driver: bridge

volumes:
  # This volume needs to be setup only once with "docker volume create mongodata"
  # It will be stored in /var/lib/docker/volumes and managed by docker.
  mongodata:
    external: true

    
