[tool.black]
line-length = 110
include = '\.pyi?$'

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 110
split_on_trailing_comma = true
known_first_party = ["lomas_core", "lomas_server" , "lomas_client"]
skip = [".gitignore", ".devenv"]

[tool.flake8]
max-line-length = 110

[tool.mypy]
disable_error_code = ["import-untyped", "import-not-found"]

[[tool.mypy.overrides]]
module = "lomas_server.tests.*"
disable_error_code = ["arg-type", "attr-defined"]

[tool.pylint.main]
ignore-patterns = "test_*.py"
max-line-length = 110

[tool.pylint."messages control"]
disable = [
    "fixme",
    "import-error",
    "duplicate-code",
    "too-many-lines",
    "too-many-locals",
    "no-name-in-module",
    "too-many-arguments",
    "too-few-public-methods",
    "dangerous-default-value",
    "missing-module-docstring",
    "logging-fstring-interpolation",
]

[tool.pydocstringformatter]
write = true
max-line-length = 110
