[tool.black]
line-length = 110
include = '\.pyi?$'
extend_exclude = '\.ipynb'

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 110
split_on_trailing_comma = true
known_first_party = ["lomas_core", "lomas_server", "lomas_client"]
skip = [".gitignore", ".devenv"]

[tool.flake8]
max-line-length = 110
extend_exclude = [".devenv", "docs"]
extend-ignore=["E501", "W503"]

[tool.mypy]
plugins = ['pydantic.mypy']
disable_error_code = ["import-untyped", "import-not-found"]
exclude = [ 'setup\.py', 'docs' ]
no_site_packages = true

[[tool.mypy.overrides]]
module = "lomas_server.tests.*"
disable_error_code = [ "attr-defined" ]

[tool.pylint.main]
max-line-length = 110
ignore-patterns = "test_*.py"
recursive = "yes"
ignore-paths = ".devenv,docs"

[tool.pylint."messages control"]
disable = [
    "fixme",
    "import-error", # fails in git-runner but not locally ?
    "duplicate-code",
    "too-many-locals",
    "logging-not-lazy",
    "undefined-variable", # handled by flake8
    "too-many-arguments",
    "too-few-public-methods",
    "dangerous-default-value",
    "missing-module-docstring",
    "logging-fstring-interpolation",
    "too-many-positional-arguments",
]

[tool.pydocstringformatter]
max-line-length = 110
write = true
exclude = [ ".devenv/**/*.py" ] # pydocstringformatter uses a wierd full path matching from glob.iglob

[tool.pytest.ini_options]
collect_ignore = ["*/test_streamlit_app_page_b.py"]
markers = [
  "long: marks test as long (deselect with '-m \"not long\"')",
]
