[project]
name = "lomas"
version = "0.4.1"
requires-python = '>=3.11'
dependencies = [
  "lomas-core",
  "lomas-client",
  "lomas-server[all]",
  "torch>=2.6", # explicit torch dependency to get cpu-only impl. see: uv.sources
]

[project.optional-dependencies]
test = [
  "ruff>=0.11",
  "mypy>=1.15",
  "coverage>=7.6",
  "pytest>=8.3",
  "pytest-cov>=6.0",
]

# workspace setup for uv
[tool.uv.sources]
lomas-core = { workspace = true }
lomas-client = { workspace = true }
lomas-server = { workspace = true }
torch = [{ index = "pytorch-cpu" }]

[tool.uv.workspace]
members = [ "core", "client", "server" ]

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

# workspace setup for setuptools (uv build)
[tool.setuptools.package-dir]
lomas-core = "core/lomas_core"
lomas-client = "client/lomas_client"
lomas-server = "server/lomas_server"

[tool.ruff]
line-length = 110
exclude = [
  "*.ipynb",
  ".devenv",
]

[tool.ruff.lint]
# ruff linter -> get available linter list
select = [
  "I", # isort
  "E", # pycodestyle
  "F", # Pyflakes
  "UP", # pyupgrade
  "PL", #Pylint
  "SIM", # flake8-simplify
  "N", # pep8-naming
  "D", # pydocstyle
  "FAST001", "FAST003", # FastAPI lint
]
ignore = [
  "E501",
  "PLR2004", #Magic value used in comparison
  "PLR0913", #too-many-arguments
  "PLR0914", #too-many-locals
  "PLR0915", #too-many-statements
  "N812", #lowercase-imported-as-non-lowercase
  "D10", # Missing docstring in public module/package/__init__
  "D401", # First line of docstring should be in imperative mood
]
isort.split-on-trailing-comma = true
isort.known-first-party = ["lomas_core", "lomas_server", "lomas_client"]
pydocstyle.convention = "pep257"
pep8-naming.extend-ignore-names = ["*Exception"]

[tool.mypy]
plugins = ['pydantic.mypy']
disable_error_code = ["import-untyped", "import-not-found"]
exclude = [ 'setup\.py', 'docs' ]
no_site_packages = true

[[tool.mypy.overrides]]
module = "lomas_server.tests.*"
disable_error_code = [ "attr-defined" ]
