# type: ignore

# This file was autogenerated by devenv.

from jupyter_server.auth import passwd

c = get_config()  # noqa: F821

password: str = "dprocks"
c.NotebookApp.password = passwd(password)

c.NotebookApp.port = 8888
