{
  pkgs,
  lib,
  config,
  ...
}:

let
  cfg = config.dockerEnv;

  inherit (lib)
    types
    mkIf
    mkOption
    mkEnableOption
    ;

  # attribute Set to KEY=VALUE format
  toINI = lib.generators.toKeyValue { };

  # Filter env variable by their prefix
  filterEnvPrefix = prefix: lib.filterAttrs (name: value: lib.strings.hasPrefix prefix name) config.env;
in
{
  options.dockerEnv = {
    enable = mkEnableOption "Enable Support for Docker Env";
  };

  config = mkIf cfg.enable {
    tasks = {
      "filegen:env_docker_compose" = {
        before = [ "devenv:enterShell" ];
        exec = ''
          cat > $DEVENV_ROOT/server/configs/.env.docker-compose <<EOF
          # This file was autogenerated by devenv

          # Lomas service
          LOMAS_SERVICE_PORT=${toString config.lomas.port}

          # Keycloak
          LOMAS_KC_PORT=${toString config.lomas.keycloak.httpPort}
          LOMAS_KC_ADMIN_USER=${config.lomas.keycloak.bootstrapAdminUser}
          LOMAS_KC_ADMIN_PWD=${config.lomas.keycloak.bootstrapAdminPass}

          # RabbitMQ
          LOMAS_RABBIT_MQ_PORT=${toString config.lomas.rabbitmq.port}
          LOMAS_RABBIT_MQ_MGMT_PORT=${toString config.lomas.rabbitmq.portManagement}
          LOMAS_RABBIT_MQ_USER=${config.lomas.rabbitmq.user}
          LOMAS_RABBIT_MQ_PASS=${config.lomas.rabbitmq.password}

          # MongoDB
          LOMAS_MONGO_PORT=${toString config.lomas.mongo.port}
          LOMAS_MONGO_ROOT_USER=${config.lomas.mongo.initialUser}
          LOMAS_MONGO_ROOT_PWD=${config.lomas.mongo.initialPassword}
          LOMAS_MONGO_DATABASE=${config.lomas.mongo.dbName}

          # Dashboard
          LOMAS_DASHBOARD_PORT=${toString config.lomas.dashboard.port}

          # MinIO
          LOMAS_MINIO_PORT=${toString config.lomas.minio.port}
          LOMAS_MINIO_CONSOLE_PORT=${toString config.lomas.minio.console_port}
          LOMAS_MINIO_ROOT_USER=${config.lomas.minio.rootUser}
          LOMAS_MINIO_ROOT_PWD=${config.lomas.minio.rootPassword}

          # Telemetry
          LOMAS_OTEL_PORT=${toString config.lomas.telemetry.services.otlp.ports.grpc}
          LOMAS_MONGO_COLLECTOR_PORT=${toString config.lomas.telemetry.services.mongodbExporter.port}

          # Client
          LOMAS_CLIENT_PORT=${toString config.lomas.client.jupyter.port}
          EOF
        '';
      };

      "filegen:env_docker_compose_service" =
        let
          serviceEnvVar = filterEnvPrefix "LOMAS_SERVICE_";
          serviceEnvVarFinal = serviceEnvVar // {
            LOMAS_SERVICE_server__host_ip = "0.0.0.0";
            LOMAS_SERVICE_amqp__url = "amqp://rabbitmq:${toString config.lomas.rabbitmq.port}";
            LOMAS_SERVICE_authenticator__keycloak_url = "http://keycloak:${toString config.lomas.keycloak.httpPort}";
            LOMAS_SERVICE_admin_database__url = "mongodb://mongodb:${toString config.lomas.mongo.port}/${config.lomas.mongo.dbName}";
            LOMAS_SERVICE_telemetry__collector_endpoint = "http://otel-collector:${toString config.lomas.telemetry.services.otlp.ports.grpc}";
          };
        in
        {
          before = [ "devenv:enterShell" ];
          exec = ''
            cat > $DEVENV_ROOT/server/configs/.env.lomas_service <<EOF
            # This file was autogenerated by devenv
            ${toINI serviceEnvVarFinal}
            EOF
          '';
        };

      "filegen:env_docker_compose_client" =
        let
          clientEnvVar = filterEnvPrefix "LOMAS_CLIENT_";
          clientEnvVarFinal = clientEnvVar // {
            LOMAS_CLIENT_APP_URL = "http://lomas_server:${toString config.lomas.port}";
            LOMAS_CLIENT_KEYCLOAK_URL = "http://keycloak:${toString config.lomas.keycloak.httpPort}";
            LOMAS_CLIENT_telemetry__collector_endpoint = "http://otel-collector:${toString config.lomas.telemetry.services.otlp.ports.grpc}";
          };
        in
        {
          before = [ "devenv:enterShell" ];
          exec = ''
            cat > $DEVENV_ROOT/server/configs/.env.lomas_client <<EOF
            # This file was autogenerated by devenv
            ${toINI clientEnvVarFinal}
            EOF
          '';
        };

      "filegen:env_docker_compose_kc_setup" =
        let
          kcEnvVar = filterEnvPrefix "LOMAS_KC_";
          kcEnvVarFinal = kcEnvVar // {
            LOMAS_KC_SETUP_KEYCLOAK_URL = "http://keycloak:${toString config.lomas.keycloak.httpPort}";
          };
        in
        {
          before = [ "devenv:enterShell" ];
          exec = ''
            cat > $DEVENV_ROOT/server/configs/administration/.env.keycloak_setup <<EOF
            # This file was autogenerated by devenv
            ${toINI kcEnvVarFinal}
            EOF
          '';
        };

      "filegen:env_docker_compose_admin" =
        let
          adminVar = filterEnvPrefix "LOMAS_ADMIN_";
          adminVarFinal = adminVar // {
            LOMAS_ADMIN_KC_CONFIG__URL = "http://keycloak:${toString config.lomas.keycloak.httpPort}";
            LOMAS_ADMIN_MG_CONFIG__URL = "mongodb://mongodb:${toString config.lomas.mongo.port}/${config.lomas.mongo.dbName}";
            LOMAS_ADMIN_DATASET_YAML = "/collections/dataset_collection.yaml";
            LOMAS_ADMIN_PATH_PREFIX = "/data";
          };
        in
        {
          before = [ "devenv:enterShell" ];
          exec = ''
            cat > $DEVENV_ROOT/server/configs/administration/.env.lomas_demo_setup <<EOF
            # This file was autogenerated by devenv
            ${toINI adminVarFinal}
            EOF
          '';
        };

      # Create .env file for those who want to use docker compose.
      "filegen:mongo_init" = {
        before = [ "devenv:enterShell" ];
        exec = ''
          cat > $DEVENV_ROOT/server/configs/mongodb_init.js <<EOF
          // This file was autogenerated by devenv.
          db.createUser({
            user: "${config.lomas.mongo.user}",
            pwd: "${config.lomas.mongo.password}",
            roles: [{ role: "readWrite", db: "${config.lomas.mongo.dbName}" }]}
          );
          EOF
        '';
      };
    };

  };
}
