{
  pkgs,
  lib,
  config,
  ...
}:

let
  cfg = config.dockerEnv;

  inherit (lib)
    mkIf
    mkEnableOption
    ;

  # Filter env variable by their prefix
  filterEnvPrefix = prefix: lib.filterAttrs (name: value: lib.strings.hasPrefix prefix name) config.env;

  inherit (lib.strings) hasPrefix substring stringLength;
  stripPath = strPath: if (hasPrefix "/" strPath) then (substring 1 (stringLength strPath) strPath) else strPath;
in
{
  options.dockerEnv = {
    enable = mkEnableOption "Enable Support for Docker Env";
  };

  config = mkIf cfg.enable {
    tasks = {
      "filegen:env_docker_compose" = {
        before = [ "devenv:enterShell" ];
        exec = ''
          cat > $DEVENV_ROOT/server/configs/.env.docker-compose <<EOF
          # This file was autogenerated by devenv

          # Lomas service
          LOMAS_SERVICE_PORT=${toString config.lomas.port}

          # Dex
          LOMAS_DEX_PORT=${toString config.lomas.dex.port}

          # RabbitMQ
          LOMAS_RABBIT_MQ_PORT=${toString config.lomas.rabbitmq.port}
          LOMAS_RABBIT_MQ_MGMT_PORT=${toString config.lomas.rabbitmq.portManagement}
          LOMAS_RABBIT_MQ_USER=${config.lomas.rabbitmq.user}
          LOMAS_RABBIT_MQ_PASS=${config.lomas.rabbitmq.password}

          # Dashboard
          LOMAS_DASHBOARD_PORT=${toString config.lomas.dashboard.port}

          #TODO: GARAGE ENV

          # Telemetry
          LOMAS_OTEL_PORT=${toString config.lomas.telemetry.services.otlp.ports.grpc}

          # Client
          LOMAS_CLIENT_PORT=${toString config.lomas.client.jupyter.port}
          EOF
        '';
      };

      "filegen:config_dex" = {
        before = [ "devenv:enterShell" ];
        exec = ''
          cat > $DEVENV_ROOT/server/configs/example_dex_config.yaml << EOF
          # This file was autogenerated by devenv

          # Minimal example config to run Lomas with dex (not production worthy!).
          issuer: http://dex:${toString config.lomas.dex.port}${config.lomas.dex.path}
          web:
            http: 0.0.0.0:${toString config.lomas.dex.port}

          storage:
            type: sqlite3
            config:
              file: /var/dex/dex.db

          grpc:
            addr: 0.0.0.0:${toString config.lomas.dex.adminPort}

          # Enable local users
          enablePasswordDB: true
          # Allow password grants with local users
          oauth2:
            passwordConnector: local

          staticClients:
            # lomas api server
            - id: ${config.lomas.oidc.clients.apiServer.client_id}
              public: false
              name: ${config.lomas.oidc.clients.apiServer.client_id}
              secret: ${config.lomas.oidc.clients.apiServer.client_secret}
            # lomas client lib
            - id: ${config.lomas.oidc.clients.apiClient}
              public: true
              name: ${config.lomas.oidc.clients.apiClient}
              redirectURIs:
                # Enables device auth flow
                - '/device/callback'
            # lomas dashboard
            - id: ${config.lomas.oidc.clients.adminDashboard.client_id}
              public: false
              name: ${config.lomas.oidc.clients.adminDashboard.client_id}
              secret: ${config.lomas.oidc.clients.adminDashboard.client_secret}
              redirectURIs:
                - http://${config.lomas.dashboard.host}:${toString config.lomas.dashboard.port}/oauth2callback
            # lomas grafana
            - id: ${config.lomas.oidc.clients.grafanaDashboard.client_id}
              public: false
              name: ${config.lomas.oidc.clients.grafanaDashboard.client_id}
              secret: ${config.lomas.oidc.clients.grafanaDashboard.client_secret}
              redirectURIs:
                - http://${config.lomas.telemetry.services.grafana.host}:${toString config.lomas.telemetry.services.grafana.port}/login/generic_oauth

          staticPasswords:
            # Beware: static passwords cannot be deleted in dex.
          EOF
        '';
      };

    };

    outputs =
      let
        LOMAS_ADMIN_USER_YAML = "/data/collections/user_collection.yaml";
        LOMAS_ADMIN_DATASET_YAML = "/data/collections/dataset_collection.yaml";
      in
      rec {
        lomas-oci-raw = pkgs.dockerTools.buildLayeredImage {
          name = "lomas-oci-raw";
          tag = "latest";
          contents = builtins.attrValues {
            inherit (pkgs.dockerTools) binSh usrBinEnv caCertificates;
            inherit (pkgs)
              bashInteractive
              coreutils-full
              dnsutils
              wget
              curl
              which
              file
              bind
              git
              ;
            inherit (config.outputs) lomas-env;
            lomas-dashboard = (
              pkgs.writeShellScriptBin "lomas-dashboard" ''
                cd ${config.outputs.lomas-env}/lib/python*/site-packages/
                streamlit run lomas-server/administration/dashboard/about.py
              ''
            );
          };
          extraCommands = ''
            install -dm 1777 tmp
            install -Dm 644 ${../server/data/collections/user_collection.yaml} ${stripPath LOMAS_ADMIN_USER_YAML}
            install -Dm 644 ${../server/data/collections/dataset_collection.yaml} ${stripPath LOMAS_ADMIN_DATASET_YAML}

            install -dm 755 data/collections/
            cp -r --no-preserve=all ${../server/data/collections}/metadata data/collections/
            install -dm 755 data/datasets/
            cp -r --no-preserve=all ${../server/data/datasets/covid_synthetic_data.csv} data/datasets/covid_synthetic_data.csv
          '';
          config = {
            Cmd = [
              "lomas"
              "start"
            ];
            Env = lib.mapAttrsToList (name: value: "${name}=${toString value}") {
              inherit LOMAS_ADMIN_USER_YAML LOMAS_ADMIN_DATASET_YAML;
            };
            Volumes = {
              "/data/collections" = { };
              "/data/datasets" = { };
            };
          };
          maxLayers = 2;
        };

        lomas-oci = pkgs.dockerTools.buildLayeredImage {
          name = "lomas-oci";
          tag = "latest";
          fromImage = lomas-oci-raw;
          config = with config.lomas; {
            Cmd = [
              "lomas"
              "start"
            ];
            Env = lib.mapAttrsToList (name: value: "${name}=${toString value}") (
              (filterEnvPrefix "LOMAS_SERVICE_")
              // (filterEnvPrefix "LOMAS_CLIENT_")
              // (filterEnvPrefix "LOMAS_ADMIN_")
              // (filterEnvPrefix "STREAMLIT_")
              // {
                LOMAS_SERVICE_server__host_ip = "0.0.0.0";
                LOMAS_SERVICE_amqp__url = "amqp://rabbitmq:${toString rabbitmq.port}";
                LOMAS_SERVICE_authenticator__oidc_discovery_url = "http://dex:${toString dex.port}${dex.path}/.well-known/openid-configuration";
                LOMAS_SERVICE_telemetry__collector_endpoint = "http://otel-collector:${toString telemetry.services.otlp.ports.grpc}";
                LOMAS_SERVICE_data_directory = "/data";

                LOMAS_CLIENT_APP_URL = "http://lomas_server:${toString port}";
                LOMAS_CLIENT_OIDC_DISCOVERY_URL = "http://dex:${toString dex.port}${dex.path}/.well-known/openid-configuration";
                LOMAS_CLIENT_telemetry__collector_endpoint = "http://otel-collector:${toString telemetry.services.otlp.ports.grpc}";

                LOMAS_ADMIN_DEX_CONFIG__URL = "http://dex:${toString dex.adminPort}";
                inherit LOMAS_ADMIN_USER_YAML LOMAS_ADMIN_DATASET_YAML;
                LOMAS_ADMIN_server_service = "http://lomas_server:${toString port}";
                LOMAS_ADMIN_server_url = "http://lomas_server:${toString port}";
              }
            );
            ExposedPorts = {
              "${toString port}" = { };
              "${toString client.jupyter.port}" = { };
              "${toString dashboard.port}" = { };
            };
            Volumes = {
              "/data/collections" = { };
              "/data/datasets" = { };
            };
          };
        };
      };

  };
}
