{
  lib,
  config,
  ...
}:

let
  cfg = config.dockerEnv;

  inherit (lib)
    mkIf
    mkEnableOption
    ;
in
{
  options.dockerEnv = {
    enable = mkEnableOption "Enable Support for Docker Env";
  };

  config = mkIf cfg.enable {
    tasks = {
      "filegen:env_docker_compose" = {
        before = [ "devenv:enterShell" ];
        exec = ''
          cat > $DEVENV_ROOT/server/configs/.env.docker-compose <<EOF
          # This file was autogenerated by devenv

          # Lomas service
          LOMAS_SERVICE_PORT=${config.ports.lomas.userApiService}
          LOMAS_SERVICE_ADMIN_PORT${config.ports.lomas.adminApiService}

          # Dex
          LOMAS_DEX_PORT=${config.ports.lomas.dex.api}

          # Dashboard
          LOMAS_DASHBOARD_PORT=${config.ports.streamlit}

          #TODO: GARAGE ENV

          # Telemetry
          LOMAS_OTEL_PORT=${config.ports.otlp.grpc}

          # Client
          LOMAS_CLIENT_PORT=${config.ports.jupyter}
          EOF
        '';
      };

      "filegen:config_dex" = {
        before = [ "devenv:enterShell" ];
        exec = ''
          cat > $DEVENV_ROOT/server/configs/example_dex_config.yaml << EOF
          # This file was autogenerated by devenv

          # Minimal example config to run Lomas with dex (not production worthy!).
          issuer: http://dex:${config.ports.lomas.dex.api}${config.lomas.dex.path}
          web:
            http: 0.0.0.0:${config.ports.lomas.dex.api}

          storage:
            type: sqlite3
            config:
              file: /var/dex/dex.db

          grpc:
            addr: 0.0.0.0:${config.ports.lomas.dex.admin}

          # Enable local users
          enablePasswordDB: true
          # Allow password grants with local users
          oauth2:
            passwordConnector: local

          staticClients:
            # lomas api server
            - id: ${config.lomas.oidc.clients.apiServer.client_id}
              public: false
              name: ${config.lomas.oidc.clients.apiServer.client_id}
              secret: ${config.lomas.oidc.clients.apiServer.client_secret}
            # lomas client lib
            - id: ${config.lomas.oidc.clients.apiClient}
              public: true
              name: ${config.lomas.oidc.clients.apiClient}
              redirectURIs:
                # Enables device auth flow
                - '/device/callback'
            # lomas dashboard
            - id: ${config.lomas.oidc.clients.adminDashboard.client_id}
              public: false
              name: ${config.lomas.oidc.clients.adminDashboard.client_id}
              secret: ${config.lomas.oidc.clients.adminDashboard.client_secret}
              redirectURIs:
                - http://${config.lomas.dashboard.host}:${config.ports.streamlit}/oauth2callback
            # lomas grafana
            - id: ${config.lomas.oidc.clients.grafanaDashboard.client_id}
              public: false
              name: ${config.lomas.oidc.clients.grafanaDashboard.client_id}
              secret: ${config.lomas.oidc.clients.grafanaDashboard.client_secret}
              redirectURIs:
                - http://${config.lomas.telemetry.services.grafana.host}:${toString config.lomas.telemetry.services.grafana.port}/login/generic_oauth

          staticPasswords:
            # Beware: static passwords cannot be deleted in dex.
          EOF
        '';
      };

    };
  };
}
