{
  pkgs,
  lib,
  config,
  ...
}:

let
  cfg = config.lomas;

  inherit (lib)
    types
    mkIf
    mkOption
    mkEnableOption
    ;

  clientIdSecret = types.submodule {
    options.client_id = mkOption {
      type = types.str;
    };
    options.client_secret = mkOption {
      type = types.str;
    };
  };
in
{
  options.lomas = {
    enable = mkEnableOption "Enable Lomas Itself";

    host = mkOption {
      type = types.str;
      default = "localhost";
      example = "lomas-server.domain";
      description = "Lomas Server address";
    };

    port = mkOption {
      type = types.int;
      description = "Lomas Server port";
    };

    dashboard.host = mkOption {
      type = types.str;
      default = "localhost";
      example = "lomas-dashboard.domain";
      description = "Lomas Dashboard address";
    };

    dashboard.port = mkOption {
      type = types.int;
      description = "Lomas Dashboard port";
    };

    realm = mkOption {
      type = types.str;
      default = "lomas";
      description = "Lomas Server Authentication Realm";
    };

    admin = mkOption {
      type = clientIdSecret;
    };

    api = mkOption {
      type = clientIdSecret;
    };

    client.jupyter.port = mkOption {
      type = types.int;
      description = "Lomas Client's Jupyter port";
    };

    client.jupyter.password = mkOption {
      type = types.str;
      description = "Lomas Client's Jupyter password";
    };

  };

  config = mkIf cfg.enable {
    processes.lomas-server = {
      exec = "python uvicorn_serve.py";
      process-compose = {
        working_dir = "$DEVENV_ROOT/server/lomas_server";
        depends_on.mongodb.condition = "process_healthy";
        readiness_probe.failure_threshold = if (config.env.LOMAS_SERVICE_server__reload == "true") then 100 else 3;
        readiness_probe.http_get = {
          scheme = "http";
          host = cfg.host;
          port = cfg.port;
          path = "/live";
        };
      };
    };

    ##########
    # WORKER #
    ##########

    processes.worker = {
      exec = "python worker.py";
      process-compose = {
        working_dir = "$DEVENV_ROOT/server/lomas_server";
        depends_on.rabbitmq.condition = "process_healthy";
        replicas = 2;
        # Un-comment to observe worker logs.
        # log_location = "$DEVENV_ROOT/logs/worker.log";
      };
    };

    processes.admin-dashboad = {
      exec = "streamlit run --server.headless true lomas_server/administration/dashboard/about.py";
      process-compose = {
        working_dir = "$DEVENV_ROOT/server";
        environment = [
          "STREAMLIT_SERVER_PORT=${toString cfg.dashboard.port}"
          "STREAMLIT_BROWSER_GATHER_USAGE_STATS=0"
        ];
      };
    };

    tasks."filegen:jupyter_config" = {
      before = [ "devenv:enterShell" ];
      exec = ''
        cat > $DEVENV_ROOT/client/configs/jupyter_notebook_config.py <<EOF
        # type: ignore
        # This file was autogenerated by devenv.
        from jupyter_server.auth import passwd

        c = get_config()  # noqa: F821
        password: str = "${cfg.client.jupyter.password}"
        c.NotebookApp.password = passwd(password)
        c.NotebookApp.port = ${toString cfg.client.jupyter.port}
        EOF
      '';
    };

  };
}
