issuer: http://127.0.0.1:5556/dex
web:
  http: 127.0.0.1:5556
storage:
  type: sqlite3
  config.file: /var/run/dex

grpc:
  addr: 127.0.0.1:5557

# Enable local users
enablePasswordDB: true
# Allow password grants with local users
oauth2:
  passwordConnector: local

staticClients:
  - id: public-client
    public: true
    name: 'Public Client'
    redirectURIs:
      - 'http://127.0.0.1/callback'
  - id: device-client
    public: true
    name: 'Device Client'
    redirectURIs:
      - '/device/callback'

# Set up an test user
staticPasswords:
  - email: "admin@example.com"
    # bcrypt hash of the string "password": $(echo password | htpasswd -BinC 10 admin | cut -d: -f2)
    hash: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W"
    username: "admin"
    userID: "08a8684b-db88-4b73-90a9-3cd1661f5466"


# Get access token
curl -sL -X POST 'http://localhost:4445/dex/token' \
  -H "Authorization: Basic $(echo -n lomas_client: | base64)" \
  -H 'Content-Type: application/x-www-form-urlencoded' \
  --data-urlencode 'grant_type=password' \
  --data-urlencode 'scope=openid profile email' \
  --data-urlencode 'username=admin@example.com' \
  --data-urlencode 'password=lomas_admin' \
  --data-urlencode 'audience=lomas_api' \
  | yq

# Get access token
curl -sL -X POST 'http://localhost:4445/dex/token' \
  -H 'Content-Type: application/x-www-form-urlencoded' \
  -d 'client_id=lomas_client' \
  -d 'grant_type=password' \
  -d 'scope=openid profile email' \
  -d 'username=admin@example.com' \
  -d 'password=lomas_admin' \
  -d 'audience=lomas_api' \
  | yq


# Get userinfo with access token
curl -sL -X GET 'http://localhost:4445/dex/userinfo' \
  -H "Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjE4Y2Q2MTJjMmViY2RkOWFkYWU0Njg2MGM5ZTdlYjIyMmUwZTgyZGUifQ.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjQ0NDUvZGV4Iiwic3ViIjoiQ2d0c2IyMWhjMTloWkcxcGJoSUZiRzlqWVd3IiwiYXVkIjoibG9tYXNfY2xpZW50IiwiZXhwIjoxNzcwMTEwMjMzLCJpYXQiOjE3NzAwMjM4MzMsImF0X2hhc2giOiItWDVqYXRmdFR3a0VUUlotTkNjeTVnIiwibmFtZSI6ImxvbWFzX2FkbWluIn0.QZ6t0a837290Awup_33rP9RFU4cg2LfZ_BgW9Kia5GEDD3s_VNEzXKcf7tOijQIm3KZqyQLur4rLsgKywyA4qfzarbxq1BLzto08Sq7q1H66VXFN245P4xeQN1odKEAC0WPKTQvfjfHjbCV0ldB6vSxqbwlanuICy1CbW0pCFEKnJFtoak5Y7eGYJSWFPXSxKAL2_nZ4PBO_3oVNP5qZr4Ssw7C21CfT5iwXMvkqgyRdznTnwNdOM1l7SEWKZshAakLQaKqMFFb1oA1_eN5dpm_igxIjKP2p50Ezd5tUv0ocsMjMtwd2wdsfCZDmLKvXMlefEuJl4Py66H0-KmnpeA" \
  -H "Content-Type: application/json" \
  | yq


# curl -sL -X POST 'http://localhost:5556/dex/device/code' \
#   -H 'Content-Type: application/x-www-form-urlencoded' \
#   --data-urlencode 'client_id=device-client' \
#   --data-urlencode 'scope=openid profile' \
#  | yq . -Poy

# curl -sL -X POST 'http://localhost:5556/dex/token' \
#   -H 'Content-Type: application/x-www-form-urlencoded' \
#   --data-urlencode 'client_id=device-client' \
#   --data-urlencode 'device_code=ke6h22plxkhdt4lemfoznhixayx4rb3m5lh4puqedps654mcqce' \
#   --data-urlencode 'grant_type=urn:ietf:params:oauth:grant-type:device_code' \
#   | yq . -Poy