apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lomas.server.fullname" . }}
  labels:
    {{- include "lomas.server.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "lomas.server.selectorLabels" . | nindent 6 }}
  replicas: 1
  template:
    metadata:
      {{- with .Values.server.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "lomas.server.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "lomas.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.server.podSecurityContext | nindent 8 }}
      imagePullSecrets:
        {{- toYaml .Values.global.imagePullSecrets | nindent 8}}
      containers:
      - name: {{ include "lomas.server.fullname" . }}
        securityContext:
            {{- toYaml .Values.server.securityContext | nindent 12 }}
        resources:
          {{- toYaml .Values.server.resources | nindent 10}}
        image: "{{ .Values.server.image.repository }}:{{ .Values.server.image.tag }}"
        command:
          - lomas-serve
        imagePullPolicy: {{ .Values.server.image.pullPolicy }}
        ports:
          - name: http
            containerPort: {{ .Values.server.runtime_args.server.host_port }}
            protocol: TCP
        volumeMounts:
          - name: data
            mountPath: /persistent-storage
        env:
        {{- range $key, $value := .Values.server.env }}
        - name: {{ $key }}
          value: "{{ $value }}"
        {{- end }}
        - name: LOMAS_SERVICE_authenticator__oidc_discovery_url
          value: "{{ .Values.server.oidc_discovery_url }}"
        - name: LOMAS_DASHBOARD_PORT
          value: "{{ .Values.dashboard.serverConfig.port }}"
        - name: LOMAS_DEX_PORT
          value: "{{ .Values.dex.service.ports.http.port }}"
        - name: LOMAS_OTEL_PORT
          value: "{{ .Values.otel.service.port}}"
        - name: LOMAS_RABBIT_MQ_MGMT_PORT
          value: "{{ .Values.rabbitmq.containerPorts.manager }}"
        - name: LOMAS_RABBIT_MQ_PASS
          value: "{{ .Values.rabbitmq.auth.password }}"
        - name: LOMAS_RABBIT_MQ_PORT
          value: "{{ .Values.rabbitmq.containerPorts.amqp }}"
        - name: LOMAS_RABBIT_MQ_USER
          value: "{{ .Values.rabbitmq.auth.username }}"
        - name: LOMAS_SERVICE_PORT
          value: "{{ .Values.server.runtime_args.server.host_port }}"
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "lomas.server.fullname" . }}
      {{- with .Values.server.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.server.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.server.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
