apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "lomas.server.dbPVCName" . }}
  labels:
    {{- include "lomas.server.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.server.pvc.db.persistence.resourcePolicy }}
    "helm.sh/resource-policy": {{ .Values.server.pvc.db.persistence.resourcePolicy }}
    {{- end }}
spec:
  accessModes:
    - {{ .Values.server.pvc.db.accessMode }}
  {{- if .Values.server.pvc.db.storageClassName }}
  storageClassName: {{ .Values.server.pvc.db.storageClassName | quote }}
  {{- end }}
  resources:
    limits:
      storage: {{ .Values.server.pvc.db.sizeLimit | quote }}
    requests:
      storage: {{ .Values.server.pvc.db.sizeRequest | quote }}