{{- if not .Values.server.runtime_args.bootstrap.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lomas.server.secretName" . }}
  labels:
    {{ include "lomas.labels" . | nindent 4}}
type: Opaque
data:
  {{ include "lomas.server.bootstrapSecretKey" . }}: {{ required ".Values.server.runtime_args.bootstrap.value or existing secret must be set." .Values.server.runtime_args.bootstrap.value | b64enc }}
{{- end }}
