{{- if not .Values.server.runtime_args.bootstrap.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lomas.server.bootstrapSecretName" . }}
  labels:
    {{ include "lomas.labels" . | nindent 4}}
type: Opaque
data:
  {{ include "lomas.server.bootstrapSecretKey" . }}: {{ required ".Values.server.runtime_args.bootstrap.value or existing secret must be set." .Values.server.runtime_args.bootstrap.value | b64enc }}
{{- end }}
---
{{- if not .Values.server.runtime_args.worker_api_key.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lomas.server.workerApiKeySecretName" . }}
  labels:
    {{ include "lomas.labels" . | nindent 4}}
type: Opaque
data:
  {{ include "lomas.server.workerApiKeySecretKey" . }}: {{ required ".Values.server.runtime_args.worker_api_key.value or existing secret must be set." .Values.server.runtime_args.worker_api_key.value | b64enc }}
{{- end }}
---
{{- if and .Values.server.runtime_args.s3Backup.enabled (not .Values.server.runtime_args.s3Backup.uri.existingSecret) }}
kind: Secret
metadata:
  name: {{ include "lomas.server.s3BackupUriSecretName" . }}
  labels:
    {{ include "lomas.labels" . | nindent 4}}
type: Opaque
data:
  {{ include "lomas.server.s3BackupUriSecretKey" . }}: {{ required ".Values.server.runtime_args.s3Backup.uri.value or existing secret must be set." .Values.server.runtime_args.s3Backup.uri.value | b64enc }}
{{- end }}
