apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lomas.server.fullname" . }}
  labels:
    {{- include "lomas.server.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "lomas.server.selectorLabels" . | nindent 6 }}
  replicas: 1
  template:
    metadata:
      {{- with .Values.server.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "lomas.server.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "lomas.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.server.podSecurityContext | nindent 8 }}
      imagePullSecrets:
        {{- toYaml .Values.global.imagePullSecrets | nindent 8}}
      containers:
      - name: {{ include "lomas.server.fullname" . }}
        securityContext:
            {{- toYaml .Values.server.securityContext | nindent 12 }}
        resources:
          {{- toYaml .Values.server.resources | nindent 10}}
        image: "{{ .Values.server.image.repository }}:{{ .Values.server.image.tag }}"
        command: ["lomas", "start"]
        imagePullPolicy: {{ .Values.server.image.imagePullPolicy }}
        ports:
          - name: user-http
            containerPort: {{ .Values.server.runtime_args.user_host_port }}
            protocol: TCP
          - name: admin-http
            containerPort: {{ .Values.server.runtime_args.admin_host_port }}
            protocol: TCP
        volumeMounts:
          - name: db
            mountPath: /db
          {{- if .Values.server.pvc.backup.enabled }}
          - name: backup
            mountPath: /backup
          {{- end }}
          {{- if .Values.server.pvc.data.enabled }}
          - name: data
            mountPath: /data
          {{- end }}
          {{- if .Values.global.configCABundle.enabled }}
          - name: trusted-cabundle
            mountPath: /etc/ssl/certs/{{ .Values.global.configCABundle.filename }}
            subPath: {{ .Values.global.configCABundle.filename }}
          {{- end }}
        env:
          - name: LOMAS_SERVER_BOOTSTRAP
            valueFrom:
              secretKeyRef:
                name: {{ include "lomas.server.bootstrapSecretName" . }}
                key: {{ include "lomas.server.bootstrapSecretKey" . }}
          - name: LOMAS_SERVER_BIND_IP
            value: "0.0.0.0"
          - name: LOMAS_SERVER_USER_HOST_PORT
            value: "{{ .Values.server.runtime_args.user_host_port }}"
          - name: LOMAS_SERVER_ADMIN_HOST_PORT
            value: "{{ .Values.server.runtime_args.admin_host_port }}"
          - name: LOMAS_SERVER_WORKER_API_KEY
            valueFrom:
              secretKeyRef:
                name: {{ include "lomas.server.workerApiKeySecretName" . }}
                key: {{ include "lomas.server.workerApiKeySecretKey" . }}
          - name: LOMAS_SERVER__ROOT_PATH
            value: "{{ .Values.server.runtime_args.root_path }}"
          - name: LOMAS_SERVER_LOG_LEVEL
            value: "{{ .Values.server.runtime_args.log_level }}"
          - name: LOMAS_SERVER_LOMAS_LOG_LEVEL
            value: "{{ .Values.server.runtime_args.lomas_log_level }}"
          - name: LOMAS_SERVER_SUBMIT_LIMIT
            value: "{{ .Values.server.runtime_args.submit_limit }}"
          - name: LOMAS_SERVER_TIME_ATTACK__METHOD
            value: "{{ .Values.server.runtime_args.time_attack.method }}"
          - name: LOMAS_SERVER_TIME_ATTACK__MAGNITUDE
            value: "{{ .Values.server.runtime_args.time_attack.magnitude }}"
          - name: LOMAS_SERVER_ADMIN_DATABASE_DIRECTORY
            value: "/db/"
          - name: LOMAS_SERVER_CLEAN_ADMIN_DATABASE
            value: "{{ .Values.server.runtime_args.clean_admin_database }}"
          {{- if not .Values.server.runtime_args.s3Backup.enabled }}
          - name: LOMAS_SERVER_BACKUP__LOCAL_DIRECTORY
            value: "/backup/"
          {{- else }}
          - name: LOMAS_SERVER_BACKUP__URI
            valueFrom:
              secretKeyRef:
                name: {{ include "lomas.server.s3BackupUriSecretName" . }}
                key: {{ include "lomas.server.s3BackupUriSecretKey" . }}
          - name: AWS_REQUEST_CHECKSUM_CALCULATION
            value: "when_required"
          - name: AWS_RESPONSE_CHECKSUM_VALIDATION
            value: "when_required"
          {{- end }}
          - name: LOMAS_SERVER_DATA_DIRECTORY
            value: "/data"
          - name: LOMAS_SERVER_AUTHENTICATOR__AUTHENTICATION_TYPE
            value: "{{ .Values.server.runtime_args.authenticator.authentication_type }}"
          - name: LOMAS_SERVER_AUTHENTICATOR__OIDC_DISCOVERY_URL
            value: "{{ .Values.server.runtime_args.authenticator.oidc_discovery_url }}"
          - name: LOMAS_SERVER_AUTHENTICATOR__QUERY_USERINFO
            value: "{{ .Values.server.runtime_args.authenticator.query_userinfo }}"
          {{- range $i, $credSecretName := (include "lomas.server.private-db-credentials-secrets" $) | fromYamlArray }}
          - name: LOMAS_SERVER_PRIVATE_DB_CREDENTIALS__{{ $i }}
            valueFrom:
              secretKeyRef:
                name: {{ $credSecretName }}
                key: private-db-credentials
          {{- end }}
          - name: LOMAS_SERVER_TELEMETRY__ENABLED
            value: "{{ .Values.server.runtime_args.telemetry.enabled }}"
          - name: LOMAS_SERVER_TELEMETRY__SERVICE_NAME
            value: "{{ .Values.server.runtime_args.telemetry.service_name }}"
          - name: LOMAS_SERVER_TELEMETRY__SERVICE_ID
            value: "{{ .Values.server.runtime_args.telemetry.service_id}}"
          - name: LOMAS_SERVER_TELEMETRY__COLLECTOR_ENDPOINT
            value: "http://{{ include "lomas.otel.fullname" . }}:{{ .Values.otel.service.port }}"
          - name: LOMAS_SERVER_TELEMETRY__COLLECTOR_INSECURE
            value: "true"
          - name: LOMAS_SERVER_OPENDP_FEATURES
            value: '{{ toJson .Values.server.runtime_args.opendp_features }}'
          {{- if .Values.global.configCABundle.enabled }}
          - name: REQUESTS_CA_BUNDLE
            value: "/etc/ssl/certs/{{ .Values.global.configCABundle.filename }}"
          - name: SSL_CERT_FILE
            value: "/etc/ssl/certs/{{ .Values.global.configCABundle.filename }}"
          {{- end }}
      volumes:
        - name: db
          persistentVolumeClaim:
            claimName: {{ include "lomas.server.dbPVCName" .}}
        {{- if .Values.server.pvc.data.enabled }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "lomas.server.dataPVCName" . }}
        {{- end }}
        {{- if .Values.server.pvc.backup.enabled }}
        - name: backup
          persistentVolumeClaim:
            claimName: {{ include "lomas.server.backupPVCName" . }}
        {{- end }}
        {{- if .Values.global.configCABundle.enabled }}
        - name: trusted-cabundle
          configMap:
            name: {{ .Values.global.configCABundle.name }}
            items:
              - key: {{ .Values.global.configCABundle.key }}
                path: {{ .Values.global.configCABundle.filename }}
        {{- end }}
      {{- with .Values.server.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.server.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.server.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
