apiVersion: v1
kind: Service
metadata:
  name: {{ include "lomas.server.fullname" . }}
  labels:
    {{- include "lomas.server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.server.service.type }}
  ports:
  - port: {{ .Values.server.service.userPort}}
    targetPort: {{ .Values.server.runtime_args.user_host_port }}
    protocol: TCP
    name: {{ .Values.server.service.userPortName }}
  - port: {{ .Values.server.service.adminPort }}
    targetPort: {{ .Values.server.runtime_args.admin_host_port }}
    protocol: TCP
    name: {{ .Values.server.service.adminPortName }}
  selector:
    {{- include "lomas.server.selectorLabels" . | nindent 4 }}
