apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lomas.worker.fullname" . }}
  labels:
    {{- include "lomas.worker.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "lomas.worker.selectorLabels" . | nindent 6 }}
  replicas: {{ .Values.worker.replicaCount }}
  template:
    metadata:
      {{- with .Values.worker.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "lomas.worker.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "lomas.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.worker.podSecurityContext | nindent 8 }}
      imagePullSecrets:
        {{- toYaml .Values.global.imagePullSecrets | nindent 8}}
      containers:
      - name: {{ include "lomas.worker.fullname" . }}
        securityContext:
            {{- toYaml .Values.worker.securityContext | nindent 12 }}
        resources:
          {{- toYaml .Values.worker.resources | nindent 10 }}
        image: "{{ .Values.server.image.repository }}:{{ .Values.server.image.tag }}"
        imagePullPolicy: {{ .Values.server.image.imagePullPolicy }}
        command: ["lomas", "work"]
        volumeMounts:
          {{- if .Values.server.pvc.data.enabled }}
          - name: data
            mountPath: /data
          {{- end }}
        env:
          - name: LOMAS_SERVER_BOOTSTRAP
            valueFrom:
              secretKeyRef:
                name: {{ include "lomas.server.bootstrapSecretName" . }}
                key: {{ include "lomas.server.bootstrapSecretKey" . }}
          - name: LOMAS_SERVER_USER_HOST_PORT
            value: "{{ .Values.server.runtime_args.user_host_port }}"
          - name: LOMAS_SERVER_ADMIN_HOST_PORT
            value: "{{ .Values.server.service.adminPort }}"
          - name: LOMAS_SERVER_WORKER_API_KEY
            valueFrom:
              secretKeyRef:
                name: {{ include "lomas.server.workerApiKeySecretName" . }}
                key: {{ include "lomas.server.workerApiKeySecretKey" . }}
          - name: LOMAS_SERVER_LOG_LEVEL
            value: "{{ .Values.server.runtime_args.log_level }}"
          - name: LOMAS_SERVER_LOMAS_LOG_LEVEL
            value: "{{ .Values.server.runtime_args.lomas_log_level }}"
          {{- range $i, $credSecretName := (include "lomas.server.private-db-credentials-secrets" $) | fromYamlArray }}
          - name: LOMAS_SERVER_PRIVATE_DB_CREDENTIALS__{{ $i }}
            valueFrom:
              secretKeyRef:
                name: {{ $credSecretName }}
                key: private-db-credentials
          {{- end }}
          - name: LOMAS_SERVER_TELEMETRY__ENABLED
            value: "{{ .Values.server.runtime_args.telemetry.enabled }}"
          - name: LOMAS_SERVER_TELEMETRY__SERVICE_NAME
            value: "{{ .Values.server.runtime_args.telemetry.service_name}}"
          - name: LOMAS_SERVER_TELEMETRY__SERVICE_ID
            value: "{{ .Values.server.runtime_args.telemetry.service_id}}"
          - name: LOMAS_SERVER_TELEMETRY__COLLECTOR_ENDPOINT
            value: "http://{{ include "lomas.otel.fullname" . }}:{{ .Values.otel.service.port }}"
          - name: LOMAS_SERVER_TELEMETRY__COLLECTOR_INSECURE
            value: "true"
          - name: LOMAS_SERVER_OPENDP_FEATURES
            value: '{{ toJson .Values.server.runtime_args.opendp_features }}'
          - name: LOMAS_SERVER_SERVER_HOST_ADDR
            value: '{{ include "lomas.server.fullname" .}}'
      volumes:
        {{- if .Values.server.pvc.data.enabled }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "lomas.server.dataPVCName" . }}
        {{- end }}
      {{- with .Values.worker.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.worker.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.worker.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
