DUMMY_NB_ROWS = 100
DUMMY_SEED = 42

CONNECT_TIMEOUT = 5
ONE_MINUTE = 60
DEFAULT_READ_TIMEOUT = ONE_MINUTE * 5
DIFFPRIVLIB_READ_TIMEOUT = ONE_MINUTE * 15
SMARTNOISE_SYNTH_READ_TIMEOUT = ONE_MINUTE * 15

SNSYNTH_DEFAULT_SAMPLES_NB = 200
