global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'localhost:9090' ]
  - job_name: 'tempo'
    static_configs:
      - targets: [ 'tempo:3200' ]
  - job_name: 'otel-collector'
    static_configs:
      - targets: [ 'otel-collector:9090' ]
  - job_name: 'loki'
    static_configs:
      - targets: [ 'loki:3100' ]
  - job_name: 'mongodb'
    static_configs:
      - targets: [ 'mongodb-exporter:9216' ]
