{{- range $i, $cred := .Values.admin.lomas_admin_users }}
{{- if not $cred.existing_secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-lomas-admin-user-%d" (include "lomas.fullname" $) $i }}
  labels:
    {{ include "lomas.labels" $ | nindent 4 }}
type: Opaque
stringData:
  lomas-admin-user: {{ $cred.username | quote }}
  lomas-admin-email: {{ $cred.email | quote }}
  lomas-admin-lastname: {{ $cred.last_name | quote }}
  lomas-admin-firstname: {{ $cred.first_name | quote }}
  lomas-admin-temp-password: {{ $cred.temp_password | quote }}
{{- end }}
{{- end }}
