
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lomas_server.fullname" . }}
  labels:
    {{- include "lomas_server.labels" . | nindent 4 }}
stringData:
  secrets.yaml: |
    admin_database:
      password: {{ index .Values.mongodb.auth.passwords 0 }}
      username: {{ index .Values.mongodb.auth.usernames 0 }}