apiVersion: v1
kind: Service
metadata:
  name: {{ include "sdd_server.fullname" . }}
  labels:
    {{- include "sdd_server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port}}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "sdd_server.selectorLabels" . | nindent 4 }}
