apiVersion: v2
name: lomas-server
description: Lomas deployment chart

type: application

version: 0.3.5

appVersion: "0.3.5"

dependencies:
  - name: mongodb
    version: "13.18.1"
    repository: https://charts.bitnami.com/bitnami
  - name: grafana
    version: "8.8.5"
    repository: https://grafana.github.io/helm-charts
  - name: tempo
    version: "1.18.0"
    repository: https://grafana.github.io/helm-charts
  - name: opentelemetry-collector
    version: "0.114.0"
    repository: https://open-telemetry.github.io/opentelemetry-helm-charts