apiVersion: v2
name: lomas-server
description: Lomas deployment chart

type: application

version: 0.4.1

appVersion: "0.4.1"

icon: "https://raw.githubusercontent.com/dscc-admin-ch/lomas/refs/heads/master/images/lomas_logo.svg"

dependencies:
  - name: mongodb
    version: "13.18.1"
    repository: https://charts.bitnami.com/bitnami
