# Default values for lomas_server.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# MongoDB 
##########################################################################
mongodb:
  resources: {}
  fullnameOverride: lomas-mongodb
  architecture: standalone
  image:
    tag: "6.0.9-debian-11-r5"
  auth:
    enabled: true
    rootUser: root
    rootPassword: root_pwd # changeme
    usernames: [user] 
    passwords: [user_pwd] # changeme
    databases: [defaultdb]
  replicaCount: 1
  discoverable:
    allow: true
  security:
    networkPolicy: 
      enabled: true
  persistence:
    # Set this to "keep" to disable data pvc deletion when uninstalling the chart.
    # Subsequent installs will use the same pvc, restoring the state of the server.
    # Note: if the runtime_args.settings.develop_mode is set to True, the server
    # state will be reset (default datasets and budgets).
    resourcePolicy: ""


# Secure Data Disclosure Fast-API server
##########################################################################

replicaCount: 1

image:
  repository: dsccadminch/lomas_server
  pullPolicy: Always
  tag: latest

# Runtime args for server
runtime_args:
  settings:
    develop_mode: True # !! Set this to false in production mode !!
    submit_limit: 300
    server:
      host_ip: "0.0.0.0"
      host_port: "80"
      log_level: "info"
      reload: True
      workers: 1 # Will be overwritten to one anyway for now.
      time_attack:
        method: "jitter" # or "stall"
        magnitude: 1
    dataset_store:
      ds_store_type: "LRU_cache"
      max_memory_usage : 512

imagePullSecrets: []
nameOverride: "lomas-server"
fullnameOverride: "lomas-server"

serviceAccount:
  # Specifies whether a service account should be created
  create: false # TODO enable this later
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "nginx"
  annotations: 
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: Prefix
  tls:
    hosts:
      - chart-example.local
  #   - secretName: chart-example-tls
  # Does not take secretName into account at all!
  # => no secret field for this cluster's ingress controller
    

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

# Lomas server not intended to be autoscaled for now
# autoscaling:
#  enabled: false
#  minReplicas: 1
#  maxReplicas: 100
#  targetCPUUtilizationPercentage: 80
#  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
