# Default values for sdd_server.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# MongoDB 
##########################################################################
mongodb:
  mongodb:
    resources: {}
    fullnameOverride: mongodb
    architecture: standalone
    image:
      tag: "4.4"
    auth:
      rootPassword: root_pwd
      username: user
      password: pwd
      database: defaultdb
    replicaCount: 1
    discoverable:
      allow: true
  fullnameOverride: mongodb
  security:
    networkPolicy: 
      enabled: true


# Secure Data Disclosure Fast-API server
##########################################################################

replicaCount: 1

image:
  repository: damienaymon/sdd-poc-server
  pullPolicy: Always
  tag: latest

imagePullSecrets: []
nameOverride: "sdd-server"
fullnameOverride: "sdd-server"

serviceAccount:
  # Specifies whether a service account should be created
  create: false # TODO enable this later
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "" # Will be automatically filled by cluster with "onyxia"
  annotations: 
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    #kubernetes.io/ingress.class: nginx
    #kubernetes.io/tls-acme: "true"
  hosts:
    - host: sdd-server.lab.sspcloud.fr
      paths:
        - path: /
          pathType: Prefix
  tls:
    hosts:
      - sdd-server.lab.sspcloud.fr
  #  - secretName: chart-example-tls
  # Does not take secretName into account at all!
  # => no secret field for this cluster's ingress controller
    

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

# SDD server not intended to be autoscaled for now
# autoscaling:
#  enabled: false
#  minReplicas: 1
#  maxReplicas: 100
#  targetCPUUtilizationPercentage: 80
#  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
