[tool.black]
line-length = 88
include = '\.pyi?$'

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 88
split_on_trailing_comma = true
src_paths = ["lomas_core"]

[tool.flake8]
max-line-length = 88

[tool.mypy]
disable_error_code = ["import-untyped", "import-not-found", "attr-defined"]

[tool.pylint.MASTER]
max-line-length = 88

[tool.pylint."MESSAGES CONTROL"]
disable = [
    "E0401",  # import-error
    "C0114",  # missing-module-docstring
    "W1203",  # use lazy % formatting in logging functions,
    "R0903",  # too-few-public-methods
]

[tool.pydocstringformatter]
write = true
max-line-length = 88
