[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
namespaces = false
where = ["."]

[project]
name = "lomas-core"
version = "0.5.1"
description = "Lomas core."
readme = "README.md"
requires-python = ">=3.11, <3.14"
authors = [
    { name = "Data Science Competence Center", email = "dscc@bfs.admin.ch" },
    { name = "Swiss Federal Statistical Office" },
]
license = "MIT"
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Natural Language :: English",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Topic :: Scientific/Engineering",
    "Topic :: Security",
    "Topic :: Software Development :: Libraries",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Typing :: Typed",
]
dependencies = [
    "returns[compatible-mypy]>=0.25",
    "diffprivlib_logger==0.0.4",
    "scikit-learn<1.9",  # due to diffprivlib
    "fastapi[standard-no-fastapi-cloud-cli]>=0.120",
    "opendp[mbi]==0.15.1",
    "polars==1.36.1",
    "opentelemetry-api>=1.29.0",
    "opentelemetry-exporter-otlp>=1.29.0",
    "opentelemetry-sdk>=1.29.0",
    "pandas>=2.2.2",
    "pydantic>=2.8",
    "pydantic-settings>=2.8",
    "csvw-eo>=0.2.1",
]

[project.urls]
Homepage = "https://github.com/dscc-admin-ch/lomas/"
