apiVersion: v1
kind: PersistentVolumeClaim
metadata:
{{- $fullname := include "lomas.tempo.fullname" . }}
  name: {{ $fullname }}
  labels:
    {{- include "lomas.tempo.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.tempo.pvc.persistence.resourcePolicy }}
    "helm.sh/resource-policy": {{ .Values.tempo.pvc.persistence.resourcePolicy }}
    {{- end }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.tempo.pvc.storageClassName }}
  storageClassName: {{ .Values.tempo.pvc.storageClassName | quote }}
  {{- end }}
  resources:
    limits:
      storage: {{ .Values.tempo.pvc.sizeLimit | quote }}
    requests:
      storage: {{ .Values.tempo.pvc.sizeRequest | quote }}