{{- if .Values.tempo.create -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "lomas.tempo.fullname" . }}
  labels:
    {{- include "lomas.tempo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.tempo.service.type }}
  selector:
    {{- include "lomas.tempo.selectorLabels" . | nindent 8 }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.tempo.service.port}}
      targetPort: {{ .Values.tempo.service.target_port}}
    - name: grpc
      port: {{ .Values.otel.service.port }}
      targetPort: {{ .Values.otel.service.target_port }}
{{- end }}