services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:4.0-management
    ports:
      - 127.0.0.1:${LOMAS_RABBIT_MQ_PORT}:${LOMAS_RABBIT_MQ_PORT}
      - 127.0.0.1:${LOMAS_RABBIT_MQ_MGMT_PORT}:${LOMAS_RABBIT_MQ_MGMT_PORT}
    environment:
      - RABBITMQ_DEFAULT_USER=${LOMAS_AMQP_USER}
      - RABBITMQ_DEFAULT_PASS=${LOMAS_AMQP_PASS}
      - RABBITMQ_NODE_PORT=${LOMAS_AMQP_PORT}

  mongodb:
    container_name: mongodb
    image: mongodb/mongodb-community-server:6.0-ubi8
    # Use only if volume is not a docker volume but a bind mount (e.g. ./data/:/data/db/)
    # The reason has to do with permissions (see https://stackoverflow.com/questions/29245216/write-in-shared-volumes-docker/29251160#29251160)
    # Still unclear why just setting chmod 777 ./data does not solve the issue.
    #user: 1000:1000
    ports:
      - 127.0.0.1:${LOMAS_MONGO_PORT}:${LOMAS_MONGO_PORT}
    volumes:
      - ./configs/mongodb_init.js:/docker-entrypoint-initdb.d/mongodb_init.js:ro
    # We use this in docker compose to have a user/password for mongodb
    # Proper deployment on a kubernetes cluster should use a helm chart
    # and parametrize a user specific to the fastAPI server.
    command:
      - "--port"
      - "${LOMAS_MONGO_PORT}"
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=${LOMAS_MONGO_ROOT_USER}
      - MONGODB_INITDB_ROOT_PASSWORD=${LOMAS_MONGO_ROOT_PWD}
      - MONGODB_INITDB_DATABASE=${LOMAS_MONGO_DATABASE}
      # add user https://stackoverflow.com/questions/42912755/how-to-create-a-db-for-mongodb-container-on-start-up/54064268#54064268
    networks:
      - test-network
  
  minio:
    container_name: minio
    image: minio/minio
    ports:
      - ${LOMAS_MINIO_PORT}:${LOMAS_MINIO_PORT}
      - ${LOMAS_MINIO_CONSOLE_PORT}:${LOMAS_MINIO_CONSOLE_PORT}
    command: server /data
    environment:
      - MINIO_ROOT_USER=${LOMAS_MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${LOMAS_MINIO_ROOT_PWD}
      - MINIO_ADDRESS=:${LOMAS_MINIO_PORT}
      - MINIO_CONSOLE_ADDRESS=:${LOMAS_MINIO_CONSOLE_PORT}
    volumes:
      - minio-data:/data
    networks:
      - test-network
      
  minio-client:
    container_name: minio-client
    image: minio/mc
    depends_on:
      - minio
    entrypoint: /bin/sh -c "
      sleep 15 &&
      mc alias set myminio http://minio:${LOMAS_MINIO_PORT} admin admin123 &&
      mc mb myminio/example || true &&
      mc cp /data/test_penguin.csv myminio/example/data/test_penguin.csv &&
      mc cp /data/metadata/penguin_metadata.yaml myminio/example/metadata/penguin_metadata.yaml &&
      mc ls --recursive --versions myminio/example"
    volumes:
      - ./lomas_server/tests/test_data/:/data
    networks:
      - test-network
networks:
  test-network:
    driver: bridge
volumes:
  minio-data:
