services:
  lomas_server:
    image: dsccadminch/lomas_server_dev
    build:
      dockerfile: ./Dockerfile
      target: lomas_server_dev
      context: ../
    container_name: lomas_server_dev
    ports:
      - ${LOMAS_SERVICE_PORT}:${LOMAS_SERVICE_PORT}
    restart: always
    env_file: ./configs/.env.lomas_service
    volumes:
      - admindata:/tmp
      - ./lomas_server:/code/server/lomas_server
      - ../core/lomas_core:/code/core/lomas_core
    depends_on:
      rabbitmq:
        condition: service_started
      minio-client:
        condition: service_completed_successfully
        restart: true
      otel-collector:
        condition: service_started
      tempo:
        condition: service_started
      loki:
        condition: service_started
      dex:
        condition: service_started
        restart: true
      lomas_demo_setup:
        condition: service_completed_successfully
        restart: true
      lomas_worker:
        condition: service_started
    networks:
      - lomas-network

  lomas_worker:
    image: dsccadminch/lomas_server_dev
    build:
      dockerfile: ./Dockerfile
      target: lomas_server_dev
      context: ../
    container_name: lomas_worker_dev
    restart: always
    command: "python -m lomas_server.worker"
    env_file: ./configs/.env.lomas_service
    volumes:
      - ./lomas_server:/code/server/lomas_server
      - ../core/lomas_core:/code/core/lomas_core
      - ./data/datasets:/data/datasets/
    depends_on:
      minio-client:
        condition: service_completed_successfully
        restart: true
      otel-collector:
        condition: service_started
      dex:
        condition: service_started
        restart: true
      rabbitmq:
        condition: service_started
        restart: true
    networks:
      - lomas-network

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:4.0-management
    ports:
      - ${LOMAS_RABBIT_MQ_PORT}:${LOMAS_RABBIT_MQ_PORT}
      - ${LOMAS_RABBIT_MQ_MGMT_PORT}:${LOMAS_RABBIT_MQ_MGMT_PORT}
    environment:
      - RABBITMQ_DEFAULT_USER=${LOMAS_RABBIT_MQ_USER}
      - RABBITMQ_DEFAULT_PASS=${LOMAS_RABBIT_MQ_PASS}
      - RABBITMQ_NODE_PORT=${LOMAS_RABBIT_MQ_PORT}
    networks:
      - lomas-network

  dex:
    container_name: dex
    image: docker.io/dexidp/dex:v2.44.0
    command: /bin/dex serve /config/dex_config.yaml
    ports:
        - ${LOMAS_DEX_PORT}:${LOMAS_DEX_PORT}
    volumes:
      - ./configs/example_dex_config.yaml:/config/dex_config.yaml
    healthcheck:
      test: ["CMD", "curl", "http://localhost/dex:${LOMAS_DEX_PORT}"]
      interval: 10s
      retries: 10
      timeout: 5s
    restart: always
    networks:
      - lomas-network

  lomas_demo_setup:
    container_name: demo_setup
    image: dsccadminch/lomas_admin_dev
    build:
      dockerfile: ./Dockerfile
      target: lomas_admin_dev
      context: ../
    depends_on:
      dex:
        condition: service_healthy
    entrypoint: /bin/sh -c "python -m lomas_server.administration.scripts.lomas_demo_setup"
    env_file: ./configs/administration/.env.lomas_demo_setup
    volumes:
      - admindata:/tmp
      - ../core/lomas_core:/code/core/lomas_core
      - ./lomas_server:/code/core/lomas_server
      - ./data/collections/metadata:/data/collections/metadata/
      - ./data/collections/dataset_collection_docker_compose.yaml:/data/collections/dataset_collection.yaml
      - ./data/collections/user_collection.yaml:/data/collections/user_collection.yaml
    networks:
      - lomas-network

  minio:
    container_name: minio
    image: minio/minio
    ports:
      - ${LOMAS_MINIO_PORT}:${LOMAS_MINIO_PORT}
      - ${LOMAS_MINIO_CONSOLE_PORT}:${LOMAS_MINIO_CONSOLE_PORT}
    command: server /data
    environment:
      - MINIO_ROOT_USER=${LOMAS_MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${LOMAS_MINIO_ROOT_PWD}
      - MINIO_ADDRESS=:${LOMAS_MINIO_PORT}
      - MINIO_CONSOLE_ADDRESS=:${LOMAS_MINIO_CONSOLE_PORT}
    networks:
      - lomas-network

  minio-client:
    container_name: minio-client
    image: minio/mc
    depends_on:
      - minio
    entrypoint: /bin/sh -c "
      sleep 15 &&
      mc alias set myminio http://minio:${LOMAS_MINIO_PORT} admin admin123 &&
      mc mb myminio/example || true &&
      mc cp /data/datasets/titanic.csv myminio/example/data/titanic.csv &&
      mc cp /data/collections/metadata/titanic_metadata.yaml myminio/example/metadata/titanic_metadata.yaml &&
      mc ls --recursive --versions myminio/example"
    volumes:
      - ./data/:/data
    networks:
      - lomas-network

  lomas_admin_dashboard:
    image: dsccadminch/lomas_admin_dev
    build:
      dockerfile: ./Dockerfile
      target: lomas_admin_dev
      context: ../
    container_name: lomas_admin_dev
    ports:
      - ${LOMAS_DASHBOARD_PORT}:${LOMAS_DASHBOARD_PORT}
    restart: always
    env_file: ./configs/administration/.env.lomas_demo_setup
    environment:
      - STREAMLIT_SERVER_PORT=${LOMAS_DASHBOARD_PORT}
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=0
    volumes:
      - ../core/lomas_core:/code/core/lomas_core
      - ./lomas_server:/code/server/lomas_server
      - ./data/:/data/
    depends_on:
      - lomas_server
    networks:
      - lomas-network

  lomas_client:
    image: dsccadminch/lomas_client_dev
    build:
      dockerfile: ./Dockerfile
      target: lomas_client_dev
      context: ../
    container_name: lomas_client
    env_file: ./configs/.env.lomas_client
    command: ["jupyter", "notebook", "--ip", "0.0.0.0", "--no-browser", "--allow-root", "--port", "${LOMAS_CLIENT_PORT}"]
    ports:
      - ${LOMAS_CLIENT_PORT}:${LOMAS_CLIENT_PORT}
    volumes:
      - ../client/lomas_client/:/code/client/lomas_client
      - ../core/lomas_core/:/code/core/lomas_core
      - ../client/configs/:/root/.jupyter/
      - ../client/notebooks/:/code/client/notebooks/
      - ./data/:/data/
    depends_on:
      - lomas_server
    networks:
      - lomas-network

  tempo:
    image: grafana/tempo:main-265ca32
    container_name: tempo
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./configs/observability/example_tempo_config.yaml:/etc/tempo.yaml
    expose:
      - 3200
      - 4317
    networks:
      - lomas-network

  otel-collector:
    image: otel/opentelemetry-collector:0.119.0
    container_name: otel-collector
    ports:
      - "4317:4317"
      - "4318:4318"
      - "13133:13133" # health_check extension
      - "1777:1777" # pprof extension
      - "55679:55679" # zpages extension
      - "9091:9090" # prometheus
    volumes:
      - ./configs/observability/example_otel_config.yaml:/etc/otel/config.yaml
    command: ["--config=/etc/otel/config.yaml"]
    depends_on:
      tempo:
        condition: service_started
      loki:
        condition: service_started
    networks:
      - lomas-network

  loki:
    image: grafana/loki:3.4
    container_name: loki
    ports:
      - "3100:3100"
    command:
      - "-config.file=/etc/loki/local-config.yaml"
    volumes:
      - ./configs/observability/example_loki_config.yaml:/etc/loki/local-config.yaml
    networks:
      - lomas-network

  prometheus:
    image: prom/prometheus:v3.2.0
    container_name: prometheus
    command:
      - --config.file=/etc/prometheus.yaml
    volumes:
      - ./configs/observability/example_prometheus_config.yaml:/etc/prometheus.yaml
    ports:
      - "9090:9090"
    networks:
      - lomas-network

  grafana:
    image: grafana/grafana:11.0.0
    container_name: grafana
    volumes:
      - ./configs/observability/grafana/example_datasources_config.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    ports:
      - "3000:3000"
    networks:
      - lomas-network

networks:
  lomas-network:
    driver: bridge
    name: lomas-network

volumes:
  admindata:
  minio-data:
