services:
  lomas_server:
    image: dsccadminch/lomas_server_dev
    build:
      dockerfile: ./Dockerfile
      target: lomas_server_dev
      context: ../
    container_name: lomas_server_dev
    ports:
      - ${LOMAS_SERVICE_PORT}:${LOMAS_SERVICE_PORT}
    restart: always
    env_file: ./configs/.env.lomas_service
    volumes:
      - ./lomas_server:/code/server/lomas_server
      - ../core/lomas_core:/code/core/lomas_core
      - ./configs/example_config.yaml:/usr/lomas_server/runtime.yaml
      - ./configs/example_secrets_local.yaml:/usr/lomas_server/secrets.yaml
    depends_on:
      minio-client:
        condition: service_completed_successfully
        restart: true
      mongodb:
        condition: service_started
        restart: true
      otel-collector:
        condition: service_started
      keycloak:
        condition: service_started
        restart: true
      keycloak_setup:
        condition: service_completed_successfully
        restart: true
    networks:
      - lomas-network

  lomas_worker:
    image: dsccadminch/lomas_server_dev
    build:
      dockerfile: ./Dockerfile
      target: lomas_server_dev
      context: ../
    container_name: lomas_worker_dev
    restart: always
    command: "python -m lomas_server.worker"
    env_file: ./configs/.env.lomas_service
    volumes:
      - ./lomas_server:/code/server/lomas_server
      - ../core/lomas_core:/code/core/lomas_core
      - ./configs/example_config.yaml:/usr/lomas_server/runtime.yaml
      - ./configs/example_secrets_local.yaml:/usr/lomas_server/secrets.yaml
    depends_on:
      minio-client:
        condition: service_completed_successfully
        restart: true
      mongodb:
        condition: service_started
        restart: true
      otel-collector:
        condition: service_started
      keycloak:
        condition: service_started
        restart: true
      keycloak_setup:
        condition: service_completed_successfully
        restart: true
      rabbitmq:
        condition: service_started
        restart: true
    networks:
      - lomas-network

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:4.0-management
    ports:
      - ${LOMAS_RABBIT_MQ_PORT}:${LOMAS_RABBIT_MQ_PORT}
      - ${LOMAS_RABBIT_MQ_MGMT_PORT}:${LOMAS_RABBIT_MQ_MGMT_PORT}
    environment:
      - RABBITMQ_DEFAULT_USER=${LOMAS_RABBIT_MQ_USER}
      - RABBITMQ_DEFAULT_PASS=${LOMAS_RABBIT_MQ_PASS}
      - RABBITMQ_NODE_PORT=${LOMAS_RABBIT_MQ_PORT}
    networks:
      - lomas-network

  mongodb:
    container_name: mongodb
    image: mongodb/mongodb-community-server:6.0-ubi8
    # Use only if volume is not a docker volume but a bind mount (e.g. ./data/:/data/db/)
    # The reason has to do with permissions (see https://stackoverflow.com/questions/29245216/write-in-shared-volumes-docker/29251160#29251160)
    # Still unclear why just setting chmod 777 ./data does not solve the issue.
    #user: 1000:1000
    ports:
      - 127.0.0.1:${LOMAS_MONGO_PORT}:${LOMAS_MONGO_PORT}
    networks:
      - lomas-network
    volumes:
      #- mongodata:/data/db/
      - ./configs/mongodb_init.js:/docker-entrypoint-initdb.d/mongodb_init.js:ro
    command:
      - "--port"
      - "${LOMAS_MONGO_PORT}"
    # We use this in docker compose to have a user/password for mongodb
    # Proper deployment on a kubernetes cluster should use a helm chart
    # and parametrize a user specific to the fastAPI server.
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=${LOMAS_MONGO_ROOT_USER}
      - MONGODB_INITDB_ROOT_PASSWORD=${LOMAS_MONGO_ROOT_PWD}
      - MONGODB_INITDB_DATABASE=${LOMAS_MONGO_DATABASE}
      # add user https://stackoverflow.com/questions/42912755/how-to-create-a-db-for-mongodb-container-on-start-up/54064268#54064268

  mongodb-exporter:
    image: bitnami/mongodb-exporter:0.43.1
    container_name: mongodb-exporter
    ports:
      - ${LOMAS_MONGO_COLLECTOR_PORT}:${LOMAS_MONGO_COLLECTOR_PORT}
    networks:
      - lomas-network
    command:
      - "--web.listen-address"
      - ":${LOMAS_MONGO_COLLECTOR_PORT}"
    environment:
      - MONGODB_URI=mongodb://${LOMAS_MONGO_ROOT_USER}:${LOMAS_MONGO_ROOT_PWD}@mongodb:${LOMAS_MONGO_PORT}
    depends_on:
      - mongodb
  
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:26.1.0
    environment:
      - KC_HTTP_PORT=${LOMAS_KC_PORT}
      - KC_BOOTSTRAP_ADMIN_USERNAME=${LOMAS_KC_ADMIN_USER}
      - KC_BOOTSTRAP_ADMIN_PASSWORD=${LOMAS_KC_ADMIN_PWD}
    command: start-dev --health-enabled=true # Dev mode is fine for local test deployments
    ports:
        - ${LOMAS_KC_PORT}:${LOMAS_KC_PORT}
    healthcheck:
      test: ["CMD-SHELL", "exec 3<>/dev/tcp/127.0.0.1/9000;echo -e 'GET /health/ready HTTP/1.1\r\nhost: http://localhost\r\nConnection: close\r\n\r\n' >&3;if [ $? -eq 0 ]; then echo 'Healthcheck Successful';exit 0;else echo 'Healthcheck Failed';exit 1;fi;"]
      interval: 10s
      retries: 10
      timeout: 5s
    restart: always
    networks:
      - lomas-network

  keycloak_setup:
    container_name: keycloak_setup
    image: dsccadminch/lomas_admin_dev
    build:
      dockerfile: ./Dockerfile
      target: lomas_admin_dev
      context: ../
    depends_on:
      keycloak:
        condition: service_healthy
    entrypoint: /bin/sh -c "python -m lomas_server.administration.scripts.keycloak_setup"
    env_file: ./configs/administration/.env.keycloak_setup
    volumes:
      - ../core/lomas_core:/code/core/lomas_core
      - ./lomas_server:/code/core/lomas_server
    networks:
      - lomas-network

  lomas_demo_setup:
    container_name: demo_setup
    image: dsccadminch/lomas_admin_dev
    build:
      dockerfile: ./Dockerfile
      target: lomas_admin_dev
      context: ../
    depends_on:
      keycloak:
        condition: service_healthy
      mongodb:
        condition: service_started
      keycloak_setup:
        condition: service_completed_successfully
    entrypoint: /bin/sh -c "python -m lomas_server.administration.scripts.lomas_demo_setup"
    env_file: ./configs/administration/.env.lomas_demo_setup
    volumes:
      - ../core/lomas_core:/code/core/lomas_core
      - ./lomas_server:/code/core/lomas_server
      - ./data/collections/metadata:/data/collections/metadata/
      - ./data/collections/dataset_collection_local.yaml:/data/collections/dataset_collection.yaml
      - ./data/collections/user_collection.yaml:/data/collections/user_collection.yaml
    networks:
      - lomas-network

  minio:
    container_name: minio
    image: minio/minio
    ports:
      - ${LOMAS_MINIO_PORT}:${LOMAS_MINIO_PORT}
      - ${LOMAS_MINIO_CONSOLE_PORT}:${LOMAS_MINIO_CONSOLE_PORT}
    command: server /data
    environment:
      - MINIO_ROOT_USER=${LOMAS_MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${LOMAS_MINIO_ROOT_PWD}
      - MINIO_ADDRESS=:${LOMAS_MINIO_PORT}
      - MINIO_CONSOLE_ADDRESS=:${LOMAS_MINIO_CONSOLE_PORT}
    #volumes:
      #- minio-data:/data
    networks:
      - lomas-network

  minio-client:
    container_name: minio-client
    image: minio/mc
    depends_on:
      - minio
    entrypoint: /bin/sh -c "
      sleep 15 &&
      mc alias set myminio http://minio:${LOMAS_MINIO_PORT} admin admin123 &&
      mc mb myminio/example || true &&
      mc cp /data/datasets/titanic.csv myminio/example/data/titanic.csv &&
      mc cp /data/collections/metadata/titanic_metadata.yaml myminio/example/metadata/titanic_metadata.yaml &&
      mc ls --recursive --versions myminio/example"
    volumes:
      - ./data/:/data
    networks:
      - lomas-network

  lomas_admin_dashboard:
    image: dsccadminch/lomas_admin_dev
    build:
      dockerfile: ./Dockerfile
      target: lomas_admin_dev
      context: ../
    container_name: lomas_admin_dev
    ports:
      - ${LOMAS_DASHBOARD_PORT}:${LOMAS_DASHBOARD_PORT}
    restart: always
    environment:
      - STREAMLIT_SERVER_PORT=${LOMAS_DASHBOARD_PORT}
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=0
    volumes:
      - ../core/lomas_core:/code/core/lomas_core
      - ./lomas_server:/code/server/lomas_server
      - ./configs/example_config.yaml:/usr/lomas_server/runtime.yaml
      - ./configs/example_secrets.yaml:/usr/lomas_server/secrets.yaml
      - ./configs/example_dashboard_config.yaml:/usr/lomas_dashboard/dashboard.yaml
      - ./data/:/data/
    depends_on:
      - lomas_server
    networks:
      - lomas-network

  client:
    image: dsccadminch/lomas_client_dev
    build:
      dockerfile: ./Dockerfile
      target: lomas_client_dev
      context: ../
    container_name: lomas_client
    environment:
      - LOMAS_SERVICE_TELEMETRY__SERVICE_NAME=lomas-client
      - LOMAS_SERVICE_telemetry__COLLECTOR_ENDPOINT=http://otel-collector:${LOMAS_OTEL_PORT}
    command: ["jupyter", "notebook", "--ip", "0.0.0.0", "--no-browser", "--allow-root", "--port", "${LOMAS_CLIENT_PORT}"]
    ports:
      - ${LOMAS_CLIENT_PORT}:${LOMAS_CLIENT_PORT}
    volumes:
      - ../client/lomas_client/:/code/client/lomas_client
      - ../core/lomas_core/:/code/core/lomas_core
      - ../client/configs/:/root/.jupyter/
      - ../client/notebooks/:/code/client/notebooks/
      - ./data/:/data/
    depends_on:
      - lomas_server
    networks:
      - lomas-network

  tempo:
    image: grafana/tempo:main-265ca32
    container_name: tempo
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./configs/observability/example_tempo_config.yaml:/etc/tempo.yaml
    expose:
      - 3200
      - 4317
    networks:
      - lomas-network

  otel-collector:
    image: otel/opentelemetry-collector:0.119.0
    container_name: otel-collector
    ports:
      - "4317:4317"
      - "4318:4318"
      - "13133:13133" # health_check extension
      - "1777:1777" # pprof extension
      - "55679:55679" # zpages extension
      - "9091:9090" # prometheus
    volumes:
      - ./configs/observability/example_otel_config.yaml:/etc/otel/config.yaml
    command: ["--config=/etc/otel/config.yaml"]
    depends_on:
      tempo:
        condition: service_started
      loki:
        condition: service_started
    networks:
      - lomas-network

  loki:
    image: grafana/loki:3.4
    container_name: loki
    ports:
      - "3100:3100"
    command:
      - "-config.file=/etc/loki/local-config.yaml"
    volumes:
      - ./configs/observability/example_loki_config.yaml:/etc/loki/local-config.yaml
    networks:
      - lomas-network

  prometheus:
    image: prom/prometheus:v3.2.0
    container_name: prometheus
    command:
      - --config.file=/etc/prometheus.yaml
    volumes:
      - ./configs/observability/example_prometheus_config.yaml:/etc/prometheus.yaml
    ports:
      - "9090:9090"
    networks:
      - lomas-network

  grafana:
    image: grafana/grafana:11.0.0
    container_name: grafana
    volumes:
      - ./configs/observability/grafana/example_datasources_config.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    ports:
      - "3000:3000"
    networks:
      - lomas-network

networks:
  lomas-network:
    driver: bridge
    name: lomas-network

volumes:
  mongodata:
  minio-data:
