x-common-build: &common

services:
  lomas_server:
    image: lomas-oci:latest
    container_name: lomas_server_dev
    command: ["lomas", "start"]
    ports:
      - ${LOMAS_SERVER_USER_PORT}:${LOMAS_SERVER_USER_PORT}
      - ${LOMAS_SERVER_ADMIN_PORT}:${LOMAS_SERVER_ADMIN_PORT}
    environment:
      - LOMAS_SERVER_user_host_port=${LOMAS_SERVER_USER_PORT}
      - LOMAS_SERVER_admin_host_port=${LOMAS_SERVER_ADMIN_PORT}
      - LOMAS_CLIENT_APP_URL=http://lomas_server:${LOMAS_SERVER_USER_PORT}
    restart: always
    volumes:
      - ./lomas_server:/code/server/lomas_server
      - ../core/lomas_core:/code/core/lomas_core
      - ./data/collections:/data/collections
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${LOMAS_SERVER_ADMIN_PORT}/live"]
      interval: 10s
      retries: 10
      timeout: 5s
    depends_on:
      otel-collector:
        condition: service_started
      tempo:
        condition: service_started
      loki:
        condition: service_started
      dex:
        condition: service_started
        restart: true
      lomas_worker:
        condition: service_started
    networks:
      - lomas-network

  lomas_worker:
    image: lomas-oci:latest
    container_name: lomas_worker_dev
    environment:
      - LOMAS_SERVER_user_host_port=${LOMAS_SERVER_USER_PORT}
      - LOMAS_SERVER_admin_host_port=${LOMAS_SERVER_ADMIN_PORT}
      - LOMAS_SERVER_server_host_addr=lomas_server
    restart: always
    command: ["lomas", "work"]
    volumes:
      - ./lomas_server:/code/server/lomas_server
      - ../core/lomas_core:/code/core/lomas_core
    depends_on:
      otel-collector:
        condition: service_started
      dex:
        condition: service_started
        restart: true
    networks:
      - lomas-network

  dex:
    container_name: dex
    image: docker.io/dexidp/dex:v2.45.1
    command: dex serve /config/dex_config.yaml
    ports:
        - ${LOMAS_DEX_PORT}:${LOMAS_DEX_PORT}
    volumes:
      - ./configs/example_dex_config.yaml:/config/dex_config.yaml
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:${LOMAS_DEX_PORT}/dex/healthz"]
      interval: 10s
      retries: 10
      timeout: 5s
    restart: always
    networks:
      - lomas-network

  lomas_demo_setup:
    container_name: demo_setup
    image: lomas-oci:latest
    environment:
      - LOMAS_ADMIN_server_url=http://lomas_server:${LOMAS_SERVER_ADMIN_PORT}
    depends_on:
      dex:
        condition: service_healthy
      lomas_server:
        condition: service_healthy
    entrypoint: lomas-demo-setup
    volumes:
      - ../core/lomas_core:/code/core/lomas_core
      - ./lomas_server:/code/core/lomas_server
      - ./data/collections/metadata:/data/collections/metadata/
      - ./data/collections/dataset_collection_docker_compose.yaml:/data/collections/dataset_collection.yaml
      - ./data/collections/user_collection.yaml:/data/collections/user_collection.yaml
    networks:
      - lomas-network

  lomas_admin_dashboard:
    image: lomas-oci:latest
    container_name: lomas_admin_dev
    ports:
      - ${LOMAS_DASHBOARD_PORT}:${LOMAS_DASHBOARD_PORT}
    restart: always
    command: ["streamlit", "run", "/code/server/lomas_server/administration/dashboard/about.py"]
    environment:
      - LOMAS_ADMIN_server_url=http://lomas_server:${LOMAS_SERVER_ADMIN_PORT}
      - STREAMLIT_SERVER_PORT=${LOMAS_DASHBOARD_PORT}
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=0
    volumes:
      - ../core/lomas_core:/code/core/lomas_core
      - ./lomas_server:/code/server/lomas_server
      - ./data/:/data/
    depends_on:
      - lomas_server
    networks:
      - lomas-network

  lomas_client:
    image: lomas-oci:latest
    container_name: lomas_client
    command: ["jupyter", "notebook", "--ip", "0.0.0.0", "--no-browser", "--allow-root", "--port", "${LOMAS_CLIENT_PORT}"]
    ports:
      - ${LOMAS_CLIENT_PORT}:${LOMAS_CLIENT_PORT}
    environment:
      - LOMAS_CLIENT_APP_URL=http://lomas_server:${LOMAS_SERVER_USER_PORT}
    volumes:
      - ../client/lomas_client/:/code/client/lomas_client
      - ../core/lomas_core/:/code/core/lomas_core
      - ../client/configs/:/root/.jupyter/
      - ../client/notebooks/:/code/client/notebooks/
      - ./data/:/data/
    depends_on:
      lomas_server:
        condition: service_healthy
      dex:
        condition: service_healthy
      lomas_demo_setup:
        condition: service_completed_successfully
        restart: true

    networks:
      - lomas-network

  tempo:
    image: grafana/tempo:main-265ca32
    container_name: tempo
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./configs/observability/example_tempo_config.yaml:/etc/tempo.yaml
    expose:
      - 3200
      - 4317
    networks:
      - lomas-network

  otel-collector:
    image: otel/opentelemetry-collector:0.119.0
    container_name: otel-collector
    ports:
      - "4317:4317"
      - "4318:4318"
      - "13133:13133" # health_check extension
      - "1777:1777" # pprof extension
      - "55679:55679" # zpages extension
      - "9091:9090" # prometheus
    volumes:
      - ./configs/observability/example_otel_config.yaml:/etc/otel/config.yaml
    command: ["--config=/etc/otel/config.yaml"]
    depends_on:
      tempo:
        condition: service_started
      loki:
        condition: service_started
    networks:
      - lomas-network

  loki:
    image: grafana/loki:3.4
    container_name: loki
    ports:
      - "3100:3100"
    command:
      - "-config.file=/etc/loki/local-config.yaml"
    volumes:
      - ./configs/observability/example_loki_config.yaml:/etc/loki/local-config.yaml
    networks:
      - lomas-network

  prometheus:
    image: prom/prometheus:v3.2.0
    container_name: prometheus
    command:
      - --config.file=/etc/prometheus.yaml
    volumes:
      - ./configs/observability/example_prometheus_config.yaml:/etc/prometheus.yaml
    ports:
      - "9090:9090"
    networks:
      - lomas-network

  grafana:
    image: grafana/grafana:11.0.0
    container_name: grafana
    volumes:
      - ./configs/observability/grafana/example_datasources_config.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    ports:
      - "3000:3000"
    networks:
      - lomas-network

networks:
  lomas-network:
    driver: bridge
    name: lomas-network
