[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
namespaces = false
where = ["."]

[project]
name = "lomas-server"
version = "0.5.1"
description = "Lomas server."
readme = "README.md"
requires-python = ">=3.11, <3.14"
authors = [
    { name = "Data Science Competence Center", email = "dscc@bfs.admin.ch" },
    { name = "Swiss Federal Statistical Office" },
]
license = "MIT"
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Natural Language :: English",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Topic :: Scientific/Engineering",
    "Topic :: Security",
    "Topic :: Software Development :: Libraries",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Typing :: Typed",
]
dependencies = [
  "lomas-core==0.5.1",
  "boto3>=1.34",
  "opentelemetry-instrumentation-fastapi>=0.50b0",
  "opentelemetry-instrumentation-logging>=0.50b0",
  "opentelemetry-instrumentation-aio-pika>=0.50b0",
  "pyjwt>=2.10",
  "aio-pika>=9.5",
  "cryptography>=44",
  "sqlglot>=27.8.0",
  "smartnoise-sql @ git+https://github.com/LancelotMarti/smartnoise-sdk?rev=391517b2b0445cff4ef62886d20f97410495c124#subdirectory=sql",
  "filelock>=3.29.0",
]

[project.optional-dependencies]
all = [
  "streamlit[auth]>=1.50",
  "bcrypt>=5.0.0",
]

[project.scripts]
lomas = "lomas_server.cli:run"
lomas-demo-setup = "lomas_server.administration.scripts.lomas_demo_setup:run"
lomas-bench = "lomas_server.administration.scripts.bench:run"

[project.urls]
Homepage = "https://github.com/dscc-admin-ch/lomas/"
