[tool.black]
line-length = 79
include = '\.pyi?$'

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 79
split_on_trailing_comma = true
src_paths = ["lomas_server"]

[tool.mypy]
disable_error_code = ["import-untyped", "import-not-found", "attr-defined"]

[tool.pylint.MASTER]
ignore-patterns = "test_*.py"

[tool.pylint."MESSAGES CONTROL"]
disable = [
    "E0401",  # import-error
    "C0114",  # missing-module-docstring
    "R0903",  # too-few-public-methods
    "E0611",  # no-name-in-module
    "W0511",  # fixme
    "C0302",  # too-many-lines
    "duplicate-code"  # duplicate-code
]

[tool.coverage.run]
relative_files = true
omit = [
    "mongodb_admin_cli.py",
    "uvicorn_serve.py"
]

[tool.coverage.report]
exclude_lines = [
    "^\\s*except\\s+InternalServerException",
    "^\\s*raise\\s+InternalServerException",
    "^\\s*except\\s+KNOWN_EXCEPTIONS",
    "^\\s*except\\s+Exception",
    "^\\s*except\\s+yaml.YAMLError",
    "^\\s*case _:"
]