{{- if .Values.grafana.create -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "lomas.grafana.fullname" . }}
  labels:
    {{- include "lomas.grafana.labels" . | nindent 4 }}
spec:
  type: {{ .Values.grafana.service.type }}
  ports:
  - port: {{ .Values.grafana.service.port}}
    targetPort: {{ .Values.grafana.service.target_port }}
    protocol: TCP
    name: http
  selector:
    {{- include "lomas.grafana.selectorLabels" . | nindent 4 }}
{{- end }}
