{
 "title": "Lomas Dashboard",
 "description": "This is Lomas' dashboard.",
 "tags": [
  "loki",
  "tempo",
  "grafana",
  "prometheus"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Endpoint distribution",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (path) (lomas_server_requests_total{app_name=\"lomas-server-app\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OpenDP Queries",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "limit": 20,
     "query": "{name=\"POST /opendp_query\"}",
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Traces on Smartnoise-SQL queries",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "limit": 20,
     "query": "{ name = \"POST /smartnoise_sql_query\" }",
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Lomas Warn, Error and Fatal Logs",
   "type": "logs",
   "description": "Logs with severity (warn, error, fatal)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{service_name=\"lomas-server-app\"} | severity_text=~\"ERROR|WARN|FATAL\""
    }
   ]
  },
  {
   "title": "Dr. Antartica Traces",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "limit": 20,
     "query": "{ span.user_name = \"Dr.Antartica\" }",
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Metric: Total number of requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "lomas_server_requests_total{method=\"POST\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Metric: Request duration seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "lomas_server_requests_duration_seconds_sum{}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AdminDB: Number of queries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "lomas_server_admindb_query_count_queries_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AdminDB: Number of update queries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "lomas_server_admindb_update_count_updates_total",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}