{
 "title": "Lomas Dashboard",
 "description": "This is Lomas' dashboard.",
 "tags": [
  "loki",
  "tempo",
  "grafana",
  "prometheus"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Lomas Dashboard",
   "type": "text",
   "description": "Visualisation of Lomas' Logs, Traces and Metrics",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 0 },
   "options": {
    "content": "# Lomas' example dashboard\n\nThis is a demo dashboard.\n\nAll panels are customizable."
   }
  },
  {
   "title": "Total number of request",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(requests_total{app_name=\"lomas_server_app\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queries endpoint distribution",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (path) (requests_total{app_name=\"lomas_server_app\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Requests in Progress per Endpoint",
   "type": "stat",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "requests_in_progress{app_name=\"lomas_server_app\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Logs on PENGUIN dataset",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "{service_name=\"lomas_server_app\"} |= `PENGUIN`"
    }
   ]
  },
  {
   "title": "All Logs (debug)",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "{service_name=\"lomas_server_app\"}"
    }
   ]
  },
  {
   "title": "Request duration (seconds)",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "requests_duration_seconds_sum{app_name=\"lomas_server_app\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Warn, Error and Fatal Level Logs",
   "type": "logs",
   "description": "Warn, error, fatal",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "{service_name=\"lomas_server_app\"} | severity_text=~\"ERROR|WARN|FATAL\""
    }
   ]
  },
  {
   "title": "Dr.Antartica Traces",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "limit": 20,
     "query": "{ span.user_name = \"Dr.Antartica\" }",
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Traces on Smartnoise-SQL queries",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "filters": [
      { "id": "0566d0ce", "operator": "=", "scope": "span" },
      {
       "id": "span-name",
       "operator": "=",
       "scope": "span",
       "tag": "name",
       "value": [ "POST /smartnoise_sql_query" ],
       "valueType": "string"
      }
     ],
     "groupBy": [
      { "id": "f247332f", "scope": "span" }
     ],
     "limit": 20,
     "query": "{}",
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Traces of OpenDP Queries",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 37 },
   "targets": [
    {
     "limit": 20,
     "query": "{name=\"POST /opendp_query\"}",
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "AdminDB: Number of queries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "lomas_server_admindb_query_count_queries_total",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}