runtime_args:
  settings:
    develop_mode: True # !! Set this to false in production mode !!
    submit_limit: 300
    time_attack:
        method: "jitter" # or "stall"
        magnitude: 1
    admin_database:
      db_type: "mongodb" # or "yaml"
      address: "mongodb" #"mongodb.user-aymond.svc.cluster.local" # or db_file: <..> for yaml db
      port: 27017
      token: abcd
      password: "user_pwd"
      username: "user"
      db_name: "defaultdb"
      #db_type: "yaml"
      #db_file: "/usr/sdd_poc_server/collections/user_collection.yaml"