runtime_args:
  settings:
    develop_mode: True # !! Set this to false in production mode !!
    submit_limit: 300
    server:
      host_ip: "0.0.0.0"
      host_port: "80"
      log_level: "info"
      reload: True
      workers: 1 # Will be overwritten to one anyway for now.
      time_attack:
        method: "jitter" # or "stall"
        magnitude: 1
    admin_database:
      db_type: "mongodb"
      address: "mongodb"
      port: 27017
      db_name: "defaultdb"
      max_pool_size: 100
      min_pool_size: 2
      max_connecting: 2
    dp_libraries:
      opendp:
        contrib: True
        floating_point: True
        honest_but_curious: True
