// This file was autogenerated by devenv.
db.createUser(
    {
        user: "user",
        pwd: "password",
        roles: [
            {
                role: "readWrite",
                db: "defaultdb"
            }
        ]
    }
);
