mongodb:
  resources: {}
  fullnameOverride: mongodb
  architecture: replicaset
  image:
    tag: "4.4"
  auth:
    rootPassword: root_pwd
    username: user_pwd
    password: pwd
    database: defaultdb
  replicaCount: 1
  discoverable:
    allow: true
fullnameOverride: mongodb
security:
  networkPolicy: 
    enabled: true