apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "lomas.caddy.configMapName" . }}
  labels:
    {{- include "lomas.caddy.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.caddy.configAnnotations | nindent 4 }}
data:
  Caddyfile: |
{{ .Values.caddy.caddyfile | indent 4 }}