apiVersion: v1
kind: Service
metadata:
  name: {{ include "lomas.caddy.fullname" . }}
  labels:
    {{- include "lomas.caddy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.caddy.service.type }}
  ports:
  - name: {{ .Values.caddy.service.portName }}
    port: {{ .Values.caddy.service.port}}
    targetPort: {{ .Values.caddy.port }}
  # - name: {{ .Values.caddy.service.httpsPortName }}
  #   port: {{ .Values.caddy.service.httpsPort}}
  #   targetPort: {{ .Values.caddy.httpsPort }}

  selector:
    {{- include "lomas.caddy.selectorLabels" . | nindent 4 }}
