apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "lomas.caddy.configMapName" . }}
  labels:
    {{- include "lomas.caddy.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.caddy.configAnnotations | nindent 4 }}
data:
  Caddyfile: |
    {
      debug
      # servers {
      #   trusted_proxies static private_ranges
      # }
    }

    {{ .Values.caddy.hostname }}:{{ .Values.caddy.port }} {
      @alice {
        header_regexp X-Auth-Request-Preferred-Username [aA]lice
      }

      handle_path /dashboard/* {
        reverse_proxy {{ include "lomas.dashboard.fullname" . }}:{{ .Values.dashboard.service.port }}
      }

      handle_path /grafana/* {
        reverse_proxy {{ include "lomas.grafana.fullname" . }}:{{ .Values.grafana.service.port }}
      }

      handle_path /auth/* {
        reverse_proxy {{ include "common.names.fullname" (dict "Release" .Release "Chart" (dict "Name" "keycloak") "Values" .Values.keycloak) -}}:{{ .Values.keycloak.service.ports.http }}
      }

      handle /oauth2/* {
        reverse_proxy {{ include "lomas.oauth2proxy.fullname" . }}:{{ .Values.oauth2proxy.service.port }} {
          header_up X-Real-IP {remote_host}
          header_up X-Forwarded-Uri {uri}
        }
      }

      handle {
        forward_auth {{ include "lomas.oauth2proxy.fullname" . }}:{{ .Values.oauth2proxy.service.port }} {
          uri /oauth2/auth
          header_up X-Real-IP {remote_host}
          copy_headers X-Auth-Request-User X-Auth-Request-Email X-Auth-Request-Preferred-Username

          @error status 401
          handle_response @error {
            redir * /oauth2/sign_in?rd=https://{host}{uri}
          }
        }

        respond @alice "Hello ... Alice"
        respond "Hello World"
      }
    }
