apiVersion: v1
kind: Service
metadata:
  name: {{ include "lomas.oauth2proxy.fullname" . }}
  labels:
    {{- include "lomas.oauth2proxy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.oauth2proxy.service.type }}
  ports:
  - port: {{ .Values.oauth2proxy.service.port}}
    targetPort: {{ .Values.oauth2proxy.port }}
    protocol: TCP
    name: {{ .Values.oauth2proxy.service.portName }}
  selector:
    {{- include "lomas.oauth2proxy.selectorLabels" . | nindent 4 }}
