apiVersion: v1
kind: Service
metadata:
  name: {{ include "lomas.oauth2-proxy.fullname" . }}
  labels:
    {{- include "lomas.oauth2-proxy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.oauth2-proxy.service.type }}
  ports:
  - port: {{ .Values.oauth2-proxy.service.port}}
    targetPort: {{ .Values.oauth2-proxy.port }}
    protocol: TCP
    name: {{ .Values.oauth2-proxy.service.portName }}
  selector:
    {{- include "lomas.oauth2-proxy.selectorLabels" . | nindent 4 }}
