{{- if not .Values.oauth2proxy.config.cookieSecretExistingSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lomas.oauth2proxy.cookieSecretName" . }}
  labels:
    {{ include "lomas.labels" . | nindent 4}}
type: Opaque
data:
  {{ include "lomas.oauth2proxy.cookieSecretKey" . }}: {{ required ".Values.oauth2proxy.config.cookieSecret" .Values.oauth2proxy.config.cookieSecret | b64enc }}
{{- end }}
---
{{- if not .Values.oauth2proxy.config.clientSecretExistingSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lomas.oauth2proxy.clientSecretName" . }}
  labels:
    {{ include "lomas.labels" . | nindent 4}}
type: Opaque
data:
  {{ include "lomas.oauth2proxy.clientSecretKey" . }}: {{ required ".Values.oauth2proxy.config.clientSecret" .Values.oauth2proxy.config.clientSecret | b64enc }}
{{- end }}
