apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lomas.oauth2proxy.fullname" . }}
  labels:
    {{- include "lomas.oauth2proxy.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "lomas.oauth2proxy.selectorLabels" . | nindent 6 }}
  replicas: 1
  template:
    metadata:
      {{- with .Values.oauth2proxy.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "lomas.oauth2proxy.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "lomas.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.oauth2proxy.podSecurityContext | nindent 8 }}
      imagePullSecrets:
        {{- toYaml .Values.global.imagePullSecrets | nindent 8}}
      {{- with .Values.oauth2proxy.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.oauth2proxy.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.oauth2proxy.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        - name: keycloak-check
          image: {{.Values.admin.curlImage.repository -}}:{{- .Values.admin.curlImage.tag }}
          imagePullPolicy: {{ .Values.admin.curlImage.pullPolicy }}
          command:
            - sh
            - -c
            - >
              until curl http://{{- include "common.names.fullname" (dict "Release" .Release "Chart" (dict "Name" "keycloak") "Values" .Values.keycloak) -}}/realms/master; do
                echo "Keycloak not ready yet";
                sleep 10;
              done;
              while true; do
                STATUS=$(curl -s -o /dev/null -w "%{http_code}" http://{{- include "common.names.fullname" (dict "Release" .Release "Chart" (dict "Name" "keycloak") "Values" .Values.keycloak) -}}/realms/{{- .Values.admin.realm -}})
                echo "Lomas realm query status: $STATUS"
                if [[ $STATUS == "200" ]]; then
                  echo "Lomas realm ready."
                  exit 0;
                fi;
                sleep 10;
              done;
          resources:
            {{ toYaml .Values.admin.keycloakSetup.resources | nindent 12}}
      containers:
      - name: oauth2proxy
        image: "{{ .Values.oauth2proxy.image.repository }}:{{ .Values.oauth2proxy.image.tag }}"
        imagePullPolicy: {{ .Values.oauth2proxy.image.pullPolicy }}
        ports:
          - name: http
            containerPort: {{ .Values.oauth2proxy.port }}
            protocol: TCP
        args:
          - --provider=keycloak-oidc
          - --http-address=0.0.0.0:{{ .Values.oauth2proxy.port }}
        env:
          - name: OAUTH2_PROXY_COOKIE_SECURE
            value: "false"
          - name: OAUTH2_PROXY_COOKIE_SECRET
            valueFrom:
              secretKeyRef:
                name: {{ template "lomas.oauth2proxy.cookieSecretName" . }}
                key: {{ template "lomas.oauth2proxy.cookieSecretKey" . }}
          - name: OAUTH2_PROXY_PASS_USER_HEADERS
            value: "true"
          - name: OAUTH2_PROXY_EMAIL_DOMAINS
            value: "{{ .Values.oauth2proxy.config.emailDomains }}"
          - name: OAUTH2_PROXY_REVERSE_PROXY
            value: "true"
          - name: OAUTH2_PROXY_SET_XAUTHREQUEST
            value: "true"
          - name: OAUTH2_PROXY_CLIENT_ID
            value: "{{ .Values.oauth2proxy.config.clientId }}"
          - name: OAUTH2_PROXY_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: {{ template "lomas.oauth2proxy.clientSecretName" . }}
                key: {{ template "lomas.oauth2proxy.clientSecretKey" . }}
          - name: OAUTH2_PROXY_PROVIDER
            value: keycloak-oidc
          - name: OAUTH2_PROXY_REDIRECT_URL
            value: "https://{{ .Values.caddy.hostname }}/oauth2/callback"
          - name: OAUTH2_PROXY_OIDC_ISSUER_URL
            value: "https://{{ .Values.caddy.hostname }}/auth/realms/lomas"
          - name: OAUTH2_PROXY_CODE_CHALLENGE_METHOD
            value: "{{ .Values.oauth2proxy.config.codeChallengeMethod }}"
          - name: OAUTH2_PROXY_WHITELIST_DOMAIN
            value: "{{ .Values.oauth2proxy.config.whitelistDomains }}"
        resources:
          {{- toYaml .Values.oauth2proxy.resources | nindent 10 }}
