apiVersion: v1
kind: Service
metadata:
  name: {{ include "lomas.oauth2Proxy.fullname" . }}
  labels:
    {{- include "lomas.oauth2Proxy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.oauth2Proxy.service.type }}
  ports:
  - port: {{ .Values.oauth2Proxy.service.port}}
    targetPort: {{ .Values.oauth2Proxy.port }}
    protocol: TCP
    name: {{ .Values.oauth2Proxy.service.portName }}
  selector:
    {{- include "lomas.oauth2Proxy.selectorLabels" . | nindent 4 }}
