apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-config
data:
  otel-collector-config.yaml: |
    receivers:
        otlp:
            protocols:
                grpc:
                    endpoint: 0.0.0.0:4317
                http:
                    endpoint: 0.0.0.0:4318
    processors:
        batch:
            timeout: 5s
    
    exporters:
        debug:
            verbosity: detailed

        otlp/tempo:
            endpoint: lomas-tempo:4317
            tls:
                insecure: true

        prometheus:
            endpoint: "0.0.0.0:9090"

        otlphttp/loki:
            endpoint: http://localhost:3100/otlp
            tls:

    extensions:
        health_check:
            endpoint: "0.0.0.0:13133"
        pprof:
            endpoint: "0.0.0.0:1777"
        zpages:
            endpoint: "0.0.0.0:55679"

    service:
        extensions: [health_check, pprof, zpages]
        pipelines:
            traces:
                receivers: [otlp]
                processors: [batch]
                exporters: [debug, otlp/tempo]
            metrics:
                receivers: [otlp]
                processors: [batch]
                exporters: [debug, prometheus]
            logs:
                receivers: [otlp]
                processors: [batch]
                exporters: [debug, otlphttp/loki]
