apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yaml: |
    global:
      scrape_interval: 10s
      evaluation_interval: 10s
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: [ 'localhost:9091' ]
      - job_name: 'tempo'
        static_configs:
          - targets: [ 'localhost:3200' ]
      - job_name: 'otel-collector'
        static_configs:
          - targets: [ 'localhost:9091' ]
      - job_name: 'loki'
        static_configs:
        - targets: [ 'localhost:3100' ]
