apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yaml: |
    global:
      scrape_interval: {{ .Values.prometheus.config.scrape_interval }}
      evaluation_interval: {{ .Values.prometheus.config.evaluation_interval }}
    scrape_configs:
      - job_name: 'otel-collector'
        static_configs:
          - targets: [ 'localhost:{{ .Values.otel.service.port }}' ]
      - job_name: 'prometheus'
        static_configs:
          - targets: [ 'localhost:{{ .Values.prometheus.service.port }}' ]
      - job_name: 'loki'
        static_configs:
          - targets: [ 'localhost:{{ .Values.loki.service.port }}' ]

