apiVersion: v1
kind: ConfigMap
metadata:
  name: tempo-config
data:
  tempo.yaml: |
    stream_over_http_enabled: true

    server:
      http_listen_port: 3200
      grpc_listen_port: 4320
      log_level: info

    querier:
      frontend_worker:
        frontend_address: query-frontend-discovery.default.svc.cluster.local:9096

    distributor:
      receivers:
        otlp:
          protocols:
            grpc:
              endpoint: "localhost:4320"

    ingester:
      max_block_duration: 5m

    compactor:
      compaction:
        block_retention: 1h

    metrics_generator:
      registry:
        external_labels:
          source: tempo
      storage:
        path: /var/tempo/generator/wal
        remote_write:
          - url: http://localhost:9091/api/v1/write
            send_exemplars: true
      traces_storage:
        path: /var/tempo/generator/traces

    storage:
      trace:
        backend: local
        wal:
          path: /var/tempo/wal
        local:
          path: /var/tempo/blocks

    overrides:
      defaults:
        metrics_generator:
          processors: [service-graphs, span-metrics, local-blocks]
          generate_native_histograms: both
