apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lomas.worker.fullname" . }}
  labels:
    {{- include "lomas.worker.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "lomas.worker.selectorLabels" . | nindent 6 }}
  replicas: {{ .Values.server.replicas }}
  template:
    metadata:
      {{- with .Values.server.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "lomas.worker.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "lomas.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.server.podSecurityContext | nindent 8 }}
      initContainers:
      # TODO: remove once the server supports connection retries to the mongodb issue 424.
      - name: mongo-check
        image: "{{ .Values.mongodb.image.registry -}}/{{- .Values.mongodb.image.image -}}:{{- .Values.mongodb.image.tag -}}"
        command:
          - sh
          - -c
          - >
            until mongosh --host {{ .Values.mongodb.fullnameOverride }} --eval 'if (!(db.hello().isWritablePrimary || db.hello().secondary)){throw new Error("Not ready")}'; do
              echo "Mongo not ready yet";
              sleep 10;
            done;
            echo "Mongo ready"
            exit 0;
      containers:
      - name: {{ .Chart.Name }}
        securityContext:
            {{- toYaml .Values.server.securityContext | nindent 12 }}
        image: "{{ .Values.server.image.repository }}:{{ .Values.server.image.tag }}"
        imagePullPolicy: {{ .Values.server.image.pullPolicy }}
        command: ["python", "-m", "lomas_server.worker"]
        ports:
          - name: http
            containerPort: {{ .Values.server.runtime_args.settings.server.host_port }}
            protocol: TCP
        env:
          - name: SERVER_SERVICE_NAME
            value: lomas-server-app
          - name: OTEL_COLLECTOR_ENDPOINT
            value: "http://{{ .Values.otel.fullnameOverride }}:{{ .Values.otel.service.port }}"
          - name: OTEL_LOG_LEVEL
            value: {{ .Values.server.runtime_args.settings.server.log_level }}
          - name: LOMAS_AMQP_USER
            value: {{ .Values.rabbitmq.auth.username }}
          - name: LOMAS_AMQP_PASS
            value: {{ .Values.rabbitmq.auth.password }}
          - name: LOMAS_AMQP_ADDR
            value: {{ .Values.rabbitmq.fullnameOverride }}
          - name: LOMAS_AMQP_PORT
            value: "{{ .Values.rabbitmq.service.ports.amqp }}"
        volumeMounts:
          - name: config-and-secrets
            readOnly: True
            mountPath: "/usr/lomas_server/"
        resources:
            {{- toYaml .Values.server.resources | nindent 12 }}
      volumes:
        - name: config-and-secrets
          projected:
            sources:
            - secret:
                name: {{ include "lomas.server.fullname" . }}
            - configMap:
                name: {{ include "lomas.server.fullname" . }}
      {{- with .Values.server.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.server.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.server.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
