name: Security with CodeQL Extended and Bandit

on:
  pull_request:
  schedule:
    - cron: '0 9 * * 1' # Monday morning at 9am

jobs:
  analyze:
    name: Analyze Python code
    runs-on: ubuntu-latest
    timeout-minutes: 360
    permissions:
      security-events: write
      packages: read
      actions: read
      contents: read

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12"]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # Set up Python for each version specified in the matrix
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    # Install and run bandit
    - name: Install Bandit
      run: pip install bandit[toml]

    - name: Run Bandit Security Scan
      run: bandit -ll -c pyproject.toml -r .  # -ll: show Medium and High severity issues only

    # Initialize CodeQL with the current Python version
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: python
        build-mode: none
        queries: security-extended

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
      with:
        category: "/language:python"