name: CI

on:
  pull_request:
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: cachix/install-nix-action@v31.10.1
        with:
          extra_nix_config: |
            accept-flake-config = true
            experimental-features = nix-command flakes cgroups auto-allocate-uids
            system-features = nixos-test benchmark big-parallel kvm
            extra-system-features = uid-range
            auto-allocate-uids = true
      - uses: cachix/cachix-action@v17
        with:
          name: lomas
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Linter & Formatter
        run: nix fmt -- --ci

      - name: Flake check
        run: nix flake check
