name: Publish to PyPI.org

on:
  pull_request:
    branches: [develop, master]
  release:
    types: [published]
  push:
    tags:
      - v*

jobs:
  pypi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: astral-sh/setup-uv@v7
        with:
          python-version: 3.13

      - name: Build Packages
        run: |
          uv build --sdist core
          uv build --sdist client

      - name: Sanity Check
        run: |
          uv run --isolated --no-project --with dist/lomas_core-*.tar.gz python -c 'import lomas_core'
          uv run --isolated --no-project --with dist/lomas_core-*.tar.gz --with dist/lomas_client-*tar.gz python -c 'import lomas_client'

      - name: Publish Packages
        if: github.event_name == 'release' || github.ref_type == 'tag'
        run: |
          uv publish -t ${{ secrets.PYPI_TOKEN }} dist/lomas_core-*.tar.gz
          uv publish -t ${{ secrets.PYPI_TOKEN }} dist/lomas_client-*tar.gz
