name: Generate docs and push to dedicated repo for publishing

on:
  pull_request:
    branches: [develop, master]
  push:
    branches: [develop, master]
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
      - uses: cachix/cachix-action@v15
        with:
          name: lomas
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Install devenv.sh
        run: nix profile install nixpkgs#devenv

      - name: Restore UV cache
        uses: actions/cache@v4
        id: uv-cache
        with:
          path: /home/runner/.cache/uv
          key: uv-store-3.12-${{ hashFiles('uv.lock') }}
          restore-keys: uv-store-3.12-

      - name: Install dependencies
        run: devenv shell -- uv pip install ".[docs]"

      - name: Build with sphinx
        run: devenv shell -- build-docs

      - name: Pushes to another repository
        if: github.event_name == 'push' || github.event_name == 'release'
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY_DOCS }}
        with:
          source-directory: pages/
          destination-github-username: 'dscc-admin-ch'
          destination-repository-name: 'lomas-docs'
          target-branch: main
          target-directory: html
