name: Publish to PyPI.org
on:
  release:
    types: [published]
jobs:
  pypi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python 11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11" 
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine
      - name: create dist
        run: |
          cd client
          python -m build
      - name: Publish package
        run: |
          twine upload dist/* -u __token__ -p ${{ secrets.PYPI_TOKEN }}