name: Generate docs and push to dedicated repo for publishing

on: 
  push: 
    branches: [ wip_215_merged-docs ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Python 11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        cd client
        pip install -r requirements.txt
        cd ../server
        pip install -r requirements.txt
        cd ../

    - name: Build with sphinx
      run: |
        if [ ! -d "docs/source/_static" ]; then
          mkdir docs/source/_static
        fi
        cp images/lomas_logo_txt.png docs/source/_static/logo.png
        sudo apt-get install pandoc
        pip install sphinx nbsphinx sphinx-rtd-theme sphinxcontrib.napoleon
        sphinx-apidoc -o docs/source ./client/lomas_client/ --tocfile client_modules
        sphinx-apidoc -o docs/source ./server/lomas_server/ --tocfile server_modules
        mkdir docs/source/notebooks
        cp -r client/notebooks/* docs/source/notebooks
        cp -r server/notebooks/* docs/source/notebooks
        cd docs
        make html
        cd build/html/
        ls
    - name: Pushes to another repository
      uses: cpina/github-action-push-to-another-repository@main
      env:
        SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY_DOCS }}
      with:
        source-directory: docs/build/html/
        destination-github-username: 'dscc-admin-ch'
        destination-repository-name: 'lomas-docs'
        target-branch: main
        target-directory: html/
