name: Publish to PyPI.org

on:
  pull_request:
    branches: [develop, master]
  release:
    types: [published]

jobs:
  pypi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: astral-sh/setup-uv@v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: uv pip install twine

      - name: Build Packages
        run: |
          uv build --sdist core
          uv build --sdist client
          uv build --sdist server

      - name: Publish Packages
        if: github.event_name == 'release'
        run: |
          twine upload dist/lomas_core*   -u __token__ -p ${{ secrets.PYPI_TOKEN }}
          twine upload dist/lomas_client* -u __token__ -p ${{ secrets.PYPI_TOKEN }}
          twine upload dist/lomas_server* -u __token__ -p ${{ secrets.PYPI_TOKEN }}

