name: Generate docs and push to dedicated repo for publishing

on:
  pull_request:
    branches: [develop, master]
  push:
    branches: [develop, master]
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: cachix/install-nix-action@v30
      - uses: cachix/cachix-action@v16
        with:
          name: lomas
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Install devenv.sh
        run: nix profile install nixpkgs/400de68cd101e8cfebffea121397683caf7f5a34#devenv

      - name: Build with sphinx
        run: devenv shell -- build-docs

      - name: Set TMPDIR for mktemp
        run: echo "TMPDIR=/tmp" >> $GITHUB_ENV

      - name: Pushes to another repository
        if: github.event_name == 'push' || github.event_name == 'release'
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY_DOCS }}
        with:
          source-directory: pages/
          destination-github-username: 'dscc-admin-ch'
          destination-repository-name: 'lomas-docs'
          target-branch: main
          target-directory: html
