name: Publish to PyPI.org
on:
  release:
    types: [published]

jobs:
  pypi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python 3.12
        uses: astral-sh/setup-uv@v5
        with:
          python-version: 3.12
      - name: Install dependencies
        run: |
          uv pip install twine
      - name: Publish core package
        run: |
          cd core
          uv build --sdist
          twine upload dist/* -u __token__ -p ${{ secrets.PYPI_TOKEN }}
      - name: Publish client package
        run: |
          cd client
          uv build --sdist
          twine upload dist/* -u __token__ -p ${{ secrets.PYPI_TOKEN }}
      - name: Publish server package
        run: |
          cd server
          uv build --sdist
          twine upload dist/* -u __token__ -p ${{ secrets.PYPI_TOKEN }}
