name: Generate client library docs and push to dedicated repo for publishing

on: 
  push: 
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Pages
      id: pages
      uses: actions/configure-pages@v3
    - name: Build with sphinx
      run: |
        pip install sphinx
        cd client
        sphinx-build -M html documentation docs
        cd docs/html/
        ls
    - name: Pushes to another repository
      uses: cpina/github-action-push-to-another-repository@main
      env:
        SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
      with:
        source-directory: client/docs/html/
        destination-github-username: 'dscc-admin-ch'
        destination-repository-name: 'lomas-client-docs'
        target-branch: main
        target-directory: html/