name: Docker Compose Tests

on:
  pull_request:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  tests:
    name: Run tests on Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: cachix/install-nix-action@v31.10.1
    - uses: cachix/cachix-action@v16
      with:
        name: lomas
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

    - name: Install devenv.sh
      run: nix profile add nixpkgs/9dcb002ca1690658be4a04645215baea8b95f31d#devenv

    - name: Run a notebook within a container
      run: |
        devenv shell
        devenv shell -- docker-load-image
        devenv shell -- docker-compose-test
