name: Server Testing

on:
  pull_request:
  workflow_dispatch:

jobs:
  tests:
    name: Run tests on Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: astral-sh/setup-uv@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        uv pip install -r core/requirements_core.txt
        uv pip install -r server/requirements_server.txt
        uv pip install -r server/requirements_streamlit.txt
    - name: Run test script
      run: |
        cd server
        chmod +x run_basic_tests.sh
        ./run_basic_tests.sh
