name: Linter checks

on: 
  pull_request:
    branches: [ develop, master]
  workflow_dispatch:
  
jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          pip install flake8-pyproject==1.2.3
          pip install mypy==1.10.0
          pip install pylint==3.1.0
      - name: flake8
        run: |
          cd client/lomas_client
          flake8 --toml-config=../pyproject.toml .
          cd ../../core/lomas_core
          flake8 --toml-config=../pyproject.toml .
          cd ../../server/lomas_server
          flake8 --toml-config=../pyproject.toml .
      - name: mypy
        run: |
          cd client
          mypy --config-file pyproject.toml .
          cd ../core
          mypy --config-file pyproject.toml .
          cd ../server
          mypy --config-file pyproject.toml .
      - name: pylint
        run: |
          cd client/lomas_client
          pylint .
          cd ../../core/lomas_core
          pylint .
          cd ../../server/lomas_server
          pylint .