name: Linter checks

on: 
  pull_request:
    branches: [ develop, master]
  workflow_dispatch:
  
jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Run linters
        run: |
          chmod +x run_linter.sh
          ./run_linter.sh --install-deps