name: Linter checks

on:
  pull_request:
    branches: [develop, master]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - uses: actions/checkout@v5
      - uses: cachix/install-nix-action@v31.10.1
      - uses: cachix/cachix-action@v17
        with:
          name: lomas
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Install devenv.sh
        run: nix profile add nixpkgs/e8be7818e19ada32105a8af937a6a473b38167ca#devenv

      - name: ruff
        run: devenv shell -- ruff check core/lomas_core client/lomas_client server/lomas_server

      - name: mypy
        run: devenv shell -- mypy core/lomas_core client/lomas_client server/lomas_server
