name: Linter checks

on:
  pull_request:
    branches: [develop, master]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          uv sync --extra test

      - name: ruff
        run: |
          for d in core/lomas_core client/lomas_client server/lomas_server; do
            ruff check "$d"
            ruff format --check "$d"
          done
