name: Linter checks

on:
  pull_request:
    branches: [ develop, master]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v4
      - name: Install the latest version of uv and set the python version to 3.12
        uses: astral-sh/setup-uv@v5
        with:
          python-version: 3.12
      - name: Install dependencies
        run: |
          uv pip install flake8-pyproject==1.2.3
          uv pip install mypy==1.10.0
          uv pip install pylint==3.1.0
      - name: flake8
        run: |
          flake8 core/lomas_core
          flake8 client/lomas_client
          flake8 server/lomas_server
      - name: mypy
        run: |
          mypy core/lomas_core
          mypy client/lomas_client
          mypy server/lomas_server
      - name: pylint
        run: |
          pylint core/lomas_core
          pylint client/lomas_client
          pylint server/lomas_server
