name: Server Tests

on:
  pull_request:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    permissions:
      # Gives the action the necessary permissions for publishing new
      # comments in pull requests.
      pull-requests: write
      # Gives the action the necessary permissions for pushing data to the
      # python-coverage-comment-action branch, and for editing existing
      # comments (to avoid publishing multiple comments in the same PR)
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Python 12
      uses: astral-sh/setup-uv@v5
      with:
        python-version: 3.12
    - name: Install dependencies
      run: |
        uv pip install -r core/requirements_core.txt
        uv pip install -r server/requirements_server.txt
        uv pip install -r server/requirements_streamlit.txt
        uv pip install coverage==7.5.3
    - name: Run test script
      run: |
        cd server
        chmod +x run_tests_and_coverage.sh
        ./run_tests_and_coverage.sh
    - name: Coverage comment
      uses: py-cov-action/python-coverage-comment-action@v3
      with:
        GITHUB_TOKEN: ${{ secrets.COVERAGE_REPORT }}
        COVERAGE_PATH: server/lomas_server/
        MINIMUM_GREEN: 95
        MINIMUM_ORANGE: 75
