name: Server Tests

on: 
  pull_request:
    branches-ignore:
      - feature/opendp_polars # TODO: remove later
  push:
    branches:
      - master
  workflow_dispatch:
  
jobs:
  tests:
    runs-on: ubuntu-latest
    permissions:
      # Gives the action the necessary permissions for publishing new
      # comments in pull requests.
      pull-requests: write
      # Gives the action the necessary permissions for pushing data to the
      # python-coverage-comment-action branch, and for editing existing
      # comments (to avoid publishing multiple comments in the same PR)
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        cd server
        pip install -r requirements.txt
        pip install coverage==7.5.3
    - name: Run test script
      run: |
        cd server
        chmod +x run_tests_and_coverage.sh
        ./run_tests_and_coverage.sh
    - name: Coverage comment
      uses: py-cov-action/python-coverage-comment-action@v3
      with:
        GITHUB_TOKEN: ${{ secrets.COVERAGE_REPORT }}
        COVERAGE_PATH: server/lomas_server/
        MINIMUM_GREEN: 95
        MINIMUM_ORANGE: 75