name: Server Tests

on:
  pull_request:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  tests:
    name: Run tests on Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
    permissions:
      # Gives the action the necessary permissions for publishing new
      # comments in pull requests.
      pull-requests: write
      # Gives the action the necessary permissions for pushing data to the
      # python-coverage-comment-action branch, and for editing existing
      # comments (to avoid publishing multiple comments in the same PR)
      contents: write

    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v26
    - uses: cachix/cachix-action@v14
      with:
        name: devenv

    - name: Install devenv.sh
      run: nix profile install nixpkgs#devenv

    - name: Set Python package
      run: |
        cat > devenv.local.nix <<EOF
        { pkgs, ... }: { languages.python.package = pkgs.python$(echo ${{ matrix.python-version }} | tr -d .); }
        EOF

    - name: Build the devenv shell
      run: devenv shell

    - name: Run all test with coverage
      shell: devenv shell bash -- -e {0}
      run: |
        ut-coverage

    - name: Coverage comment
      uses: py-cov-action/python-coverage-comment-action@v3
      with:
        GITHUB_TOKEN: ${{ secrets.COVERAGE_REPORT }}
        COVERAGE_PATH: server/lomas_server/
        MINIMUM_GREEN: 95
        MINIMUM_ORANGE: 75
